### ISSUE TITLE
NonSteadyStateOutlier00 column only exists if any events happened

### ISSUE THREAD

**Issue by celstark** [poldracklab/fmriprep#1004]
If a scan run never generates any TRs that should be flagged for non-steady-state-outlier, the column is not output at all.  So, if you have some runs or some subjects that have 1's ever and some that never do, your confounds.tsv files have different numbers of columns.  That makes things like "grab column 30" an impossible strategy.

Solution: always output these columns even if they're all 0's.

**Comment by celstark** [comment]
I just noticed that Cosine03 and Cosine04 were missing from one output as well.  Can we have a flag maybe to say "output full confound file"?

**Comment by chrisfilo** [comment]
I strongly advise against using column index when accessing tabular data. Using column names parsed from headers is a much less error prone (I actually use this very example in my [Software testing for scientists](https://neurohackweek.github.io/software-testing-for-scientists/) tutorial). Indexing tabular files by column names is supported by all major languages (in python I recommend using pandas).

Having said that we would be happy to review a pull request with the flag you mentioned.

**Comment by effigies** [comment]
To implement such an option, we would need to know upper bounds on the number of non-steady-state outliers and cosine basis functions. Non-steady-state outliers are going to be pretty limited, so that wouldn't be too bad, but we would need to be very confident in our assumption of the maximum possible outliers. The number of cosine basis functions depends on the [duration of the run and the TR](https://github.com/nistats/nistats/blob/80e3e299c7bbd8b4bb591c61421b2122a1c491a9/nistats/design_matrix.py#L97-L101), which gets a bit more complicated to future-proof.

**Comment by oesteban** [comment]
Hi @celstark, I hope these explanations fully answered your question. Please feel free to reopen the issue otherwise.
