### ISSUE TITLE
Multiecho: accept SDC warpings in T2* calculation

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1031]
Same way it accepts the HMC xforms, enable unwarping of EPIs if it was calculated

**Comment by emdupre** [comment]
Moving the conversation from #1021 here -- cc @oesteban @prantikk:

I think the tension I see in this is using the T2* map for coregistration vs. using it for subsequent Kappa/Rho calculation. Right now the T2* map isn't even connected to a data sink, but especially if it's going to become the default with multi-echo data (as @oesteban suggested), I think it makes sense to generate it by default, pipe it to the data sink, and then only pass it along for SDC if it's used in coregistration.

That being said, I think two of the steps @oesteban proposed (removing negative values from the echos and calculating T2* in a mask) are relatively non-controversial (not sure if you agree, @prantikk). The idea of clipping the histogram could be a bit more problematic down the line -- what if we added that as a function node immediately before the SDC correction ?

The one concern this brings up is dealing with normalization differences between the echos and the T2* map. Could we just apply those parameters before passing to the data sink ? WDYT ?

**Comment by tsalo** [comment]
Currently, STC, HMC, and SDC are applied before T2* calculation, after which coregistration to T1 and warping to standard are done. T2*-based coregistration was removed in #2109.

Is the goal here to apply SDC _after_ T2* calculation instead of before? I know that's a concern for some folks, although I doubt that SDC would have a major impact on T2* maps and optimally combined time series.

**Comment by emdupre** [comment]
I think the original goal was to apply after, but our understanding has evolved since then and I agree that it should be fine as-is. 

I'm fine with closing this !
