### ISSUE TITLE
Is the "-it" argument in the call to docker necessary in fmriprep-docker?

### ISSUE THREAD

**Issue by bbfrederick** [poldracklab/fmriprep#1059]
I've recently been running my preprocessing on an fairly hefty unused linux box I found in our server room.  I log in over ssh from my laptop to kick off the run, but I don't want to have to stay connected for days until its done.  The problem is, I can't detach.  If I try to detach, I get an "the input device is not a TTY" error from docker and it bails. Looking at the command fmriprep-docker generates, I tried changing the "-it" to "-i", and it _seems_ to be perfectly happy running detached with no STDIN.  Since as far as I can see, I'm never going to be asked to send any input to docker during a run, what's the rationale for requiring a connection to STDIN?  Could "-i" be made the default?

**Comment by effigies** [comment]
Possibly. Are you able to `Ctrl-C` to quit without the `-t`? If I remember correctly, that was the main thing we needed.

In the meantime, you could also use `screen`, `tmux`, or `byobu` to keep a TTY session open that you can detach from and reattach to.

**Comment by araikes** [comment]
Admittedly, this is slightly different usage, but I am able to run fmriprep across multiple participants in parallel using docker and just -i, rather than -it.

**Comment by effigies** [comment]
@araikes If you're running on a single computer and have the resources to run multiple participants simultaneously, you can use `--partcipant-label <label1> <label2> ...` to run multiple participants in the same workflow. Because there won't be dependencies, the jobs from one will not block another, and Nipype will handle resource management.

However, if you're doing it to over-commit resources (especially useful during `recon-all`, as large chunks of time may be spent with several cores committed while one is being used), then your approach may be better.

**Comment by effigies** [comment]
> Are you able to Ctrl-C to quit without the -t? If I remember correctly, that was the main thing we needed.

I just got around to checking. You cannot `Ctrl-C` without `-t`, and adding yet another option to `fmriprep-docker` does not seem worth it. If you cannot use `screen` or similar, you can copy and modify the docker command that `fmriprep-docker` generates.
