### ISSUE TITLE
SyN-SDC with T1w output space

### ISSUE THREAD

**Issue by DavidAbramian** [poldracklab/fmriprep#1062]
Hi,

I have made a few attempts to use SyN-SDC with T1w output space, resulting in a crash down the line, until I realized that the output space is required to be MNI. Is this a necessary constraint of the method itself, or could it be adapted to data in native space? It would be quite useful to have the option of native output space for working with data used for preoperative planning.

I also wonder about the use of a susceptibility distortion atlas to determine the areas that are subjected to correction. Would you consider making this optional, or does it consistently give better results?

Lastly, given that fmriprep isses a warning when starting a run with SyN-SDC together with an output space that isn't MNI, and this causes a crash later on, would it not be reasonable to halt the execution entirely instead of just issuing a warning?

Thanks!

**Comment by effigies** [comment]
> Is this a necessary constraint of the method itself, or could it be adapted to data in native space?

It's necessary for the method because the distortion atlas is in MNI space, so we need to find the MNI->T1w warp. However, to be clear, the SDC correction is applied to all outputs.

> I also wonder about the use of a susceptibility distortion atlas to determine the areas that are subjected to correction. Would you consider making this optional, or does it consistently give better results?

This is necessary to constrain the estimated deformation to areas that have at least one voxel distortion. Because EPI and T1w never perfectly align, removing this would essentially be a first-pass BOLD->T1w nonlinear registration.

> would it not be reasonable to halt the execution entirely instead of just issuing a warning?

It would, if we were sure that you would be using SyN-SDC. Currently `--use-syn-sdc` enables the option, but SDC using actual fieldmaps take priority. `--force-syn` guarantees that you will be using SyN-SDC, and we halt if MNI is not enabled, in that case. T1w->MNI registration is a very expensive step, so turning it on when we don't know that we'll either need MNI outputs or to run SyN-SDC incurs a severe penalty.

Just for some context, when these decisions were made, SyN-SDC was considered highly experimental, and a little bit of user-unfriendliness was acceptable. More people seem to be turning it on by default, so we should probably do the work of determining whether SyN-SDC will be used and enable T1w-MNI registration in that case, even if MNI outputs are disabled.
