### ISSUE TITLE
Question about parallelization 

### ISSUE THREAD

**Issue by bbfrederick** [poldracklab/fmriprep#1091]
I don't really understand the difference between --nthreads, --n_cpus, and -n-cpus.  Are they synonyms, or do they control different things?  And how do they relate to --omp-nthreads?

The reason I ask, is that I called fmriprep with --n_cpus 22, --nthreads 44, and --omp-nthreads 22, and --mem-mb 20000, on a directory with 48 subjects, and I find that everything runs nicely in parallel, all CPUs maxed out most of the time, except when running freesurfer - that seems to be done sequentially, 2 instances of recon-all at a time.  This confuses me.

This is a unix box with 2 hyper threaded 6 core processors (it says it has 24 cpus), and 24GB of RAM, so I may have been too extreme with the nthreads (I thought it would help with i/o bound processs).    So I could understand some contention  when too many processes are running, but I don't understand why freesurfer is only taking at most 2 processor slots.  Is -n-cpus different from --n_cpus?  Should I crank that up?

**Comment by effigies** [comment]
Hi @bbfrederick,

There are two actual parameters: `--n-cpus` and `--omp-nthreads`. `--n_cpus` and `--nthreads` are both synonyms for `--n-cpus`, which we keep around for historical reasons.

The difference between the two is that `--omp-nthreads` describes the maximum number of threads an individual process can use, while `--n-cpus` indicates the total number of cores we can distribute across. Not every job uses more than one thread, so often we can have more than `floor(n-cpus/omp-nthreads)` jobs running in parallel, but multi-threaded jobs can use up more than one slot.

In any event, I would actually recommend leaving these untouched, unless you want to restrict CPU usage below the actual capacity of the system (if you're submitting jobs to an HPC, for instance). The default `--n-cpus` is the number of cores on the system, so that's typically fine. `--omp-nthreads` defaults to `min(8, n-cpus - 1)`. The performance gains after 8 threads are minimal, in our experience, and leaving cores available to run other processes is the better option. We use `n-cpus - 1` so that cheap single threaded jobs can keep processing while long-running multi-threaded jobs are working.

FreeSurfer is a little bit weird in that it's a pipeline in its own right, and attempts to break it down into its components to get parallelization from [nipype](https://nipype.readthedocs.io/en/latest/) (our pipeline engine) have been stymied by the fact that they change the pipeline slightly from version to version, and tracking these changes would be a significant effort that needs to be verified for correctness with every change (not to mention supporting multiple versions). We do break the job down into some coarse chunks that nipype can parallelize a little smarter than FreeSurfer does, itself. Each of these chunks gets tagged as using `omp-nthreads` cores, even though they can spend a lot of time only using one, because at some points they do parallelize, and these speed-ups are valuable.

Anyway, I hope this gives you some better context. The short story is still: set `--n-cpus` to the maximum number of cores you want doing any work; let us set `--omp-nthreads` to the default, unless you have a really good reason (such as you want to profile fmriprep under these different conditions and see if our defaults really are as good as we think).

**Comment by bbfrederick** [comment]
Wow - thank you for the very fast and super clear answer!

Re: freesurfer - would there be anything to gain then by launching multiple fmriprep --anat-only instances using --participant-label to at least force it to run at least as many subjects as fmriprep instances at once?  Watching the machine use 2 cpus out of 24 for the last 3 days as it creeps through the list of participants has been really nerve-racking...

**Comment by effigies** [comment]
If you continue to run them all as a single workflow without `--n-cpus` (defaulting to 24) or `--omp-nthreads` (defaulting to 8), then you should at times get three of these processes (likely two from one subject and one from another) running in parallel, which will fluctuate between 3 and 24 cores as it works.

Almost certainly there would be an advantage as far as processing goes, but there is a potential to lose the OMP-induced speedups within subject, if the multi-threading steps are hit at the same time across subjects. For example, if you have 12 subjects, and are running them in independent fmriprep workflows, those times when they balloon to use 16 cores-per-subject (2 hemispheres * 8 cores) will be over-committing by 168 cores. There's also a solid chance for over-committing memory, which could really slow things down by hitting swap. So I'd be careful with how many you try to run in parallel.

It might be better to set `--omp-nthreads 4` or something, so you could get six recon nodes running in parallel.

Finally, another option would be to lie to fmriprep with `--n-cpus 32` or something, and take the performance hit if we actually do try to use all 32.

**Comment by effigies** [comment]
Please reopen if you have further questions.
