### ISSUE TITLE
[DOC] Move documentation to gh-pages

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1105]
Building documentation in RTD generates a lot of noise. We could just submit the documentation built in circle, back to github (https://github.com/oesteban/ghpages-deploy-script).

As for the analytics: https://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages

**Comment by effigies** [comment]
One thing about RTD is the archiving of old versions of the docs. Would we be abandoning that?

**Comment by oesteban** [comment]
Apparently we can't https://github.com/rtfd/readthedocs.org/issues/1083

**Comment by effigies** [comment]
Just looked through RTD settings. I believe the noise occurs because we produce PDFs along with our HTML docs, but RTD can't build the same version in parallel, so it errors and re-runs. I will note that the PDFs have some formatting issues (lots of blank pages, author list too long for the title page, and some chunks missing entirely). Do we think that anybody uses these, and that they're worth building?

**Comment by oesteban** [comment]
In my opinion, PDFs can definitely go away

**Comment by effigies** [comment]
Okay, turned off. We'll see if that cuts down on the noise. I'll close this for now. Let's reopen if the emails keep coming.

**Comment by oesteban** [comment]
We are getting memory errors on readthedocs now. I think this is going to be unavoidable.
