### ISSUE TITLE
fmriprep-docker does not list all args in docs

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#1129]
...which confuses some users https://neurostars.org/t/passing-fmriprep-arguments-to-fmriprep-docker-wrapper/1679/3

**Comment by effigies** [comment]
IMO, we should just note that all arguments are available, and that those listed are ones that modify the Docker command. I think recapitulating all of the fmriprep options will only serve to obscure the additional options that are provided.

**Comment by chrisfilo** [comment]
Fair point. Let's see if more people run into this.

Best,
Chris

**Comment by marcelzwiers** [comment]
I tried maintaining a few manually installed fmriprep versions because the readthedocs page suggested there were only a few commandline options when using the docker image. I think it should definitely be advertised more clearly that all the fmriprep options are also available when using the docker wrapper

**Comment by effigies** [comment]
Ah, yes, I'm sorry. This recently came up elsewhere and I've opened #1488. Would you have any interest in submitting a clarifying patch for the docs?

**Comment by oesteban** [comment]
Closed via #1515
