### ISSUE TITLE
Support independent jobs across sessions

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/fmriprep#1175]
It's certain that we will see more and more datasets like MyConnectome and Midnight Scan Club. To efficiently process such dataset we need to support submitting independent jobs across sessions. In practice this would mean:

- addition of `session` analysis level and `--session_label` flag for selecting sessions (more details at https://groups.google.com/forum/#!topic/bids-apps-dev/Vnx5HHudqq4)
- addition of `participant_anat` analysis level to be run before any `session` levels

**Comment by effigies** [comment]
I think one of the relevant problems to consider here is separate working directories, which will attempt to re-run anatomical. I think we need to ensure that all necessary anatomical inputs to the BOLD workflow are in the anatomical derivatives, and use those, rather than reaching into the working directory.

I think at one point I had an open issue about a DataGrabber for fmriprep derivatives. That could be a useful component here.

**Comment by oesteban** [comment]
> I think we need to ensure that all necessary anatomical inputs to the BOLD workflow are in the anatomical derivatives, and use those, rather than reaching into the working directory.

This is the key point here. +1

**Comment by poldrack** [comment]
just wanted to upvote this one again (just trying to analyze myconnectome data again).

**Comment by carolinarsm** [comment]
Also bumping this much needed feature, so +1.

**Comment by oesteban** [comment]
This will be possible when poldracklab/smriprep#107 is merged in. Can't provide an ETA, but I'd like to see this fixed within 2 months.
