### ISSUE TITLE
[BUG] ``collect_data`` dropping valid BIDS datasets

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1251]
As per https://neurostars.org/t/fmriprep-no-bold-images-found-for-participant/2245/17.

When running:
```
$ singularity exec ${MODULEDIR}/fmriprep_ver1.1.4-2018-08-06.img python -c "from fmriprep.utils.bids import collect_data; print(collect_data('<DATADIR>/Data/sourcedata_dropscans/', 'control01', None)[0])"
{'fmap': [], 'bold': [], 'sbref': [], 'flair': [], 't2w': [], 't1w': [], 'roi': []}
```
the outputs are empty. However the pybids query seems to find files:
```
$ singularity exec /work/ics/data/projects/snaglab/modules/fmriprep_ver1.1.4-2018-08-06.img python -c "from bids.grabbids import BIDSLayout; print(BIDSLayout('/work/ics/data/projects/snaglab/Projects/POKER.05/Data/sourcedata_dropscans').get(type=['T1w', 'bold'], return_type='id', target='subject'))"
['autism01', 'autism02', 'autism03', 'autism04', 'autism05', 'autism06', 'autism07', 'autism08', 'autism09', 'autism10', 'autism11', 'autism12', 'autism13', 'autism14', 'autism15', 'autism16', 'control01', 'control02', 'control03', 'control04', 'control05', 'control06', 'control07', 'control08', 'control09', 'control10', 'control11', 'control12', 'control13', 'control14', 'control15', 'control16']
```

**Comment by akhanf** [comment]
FYI we have experienced this bug just now, and found that it had to do with the number of characters in the bids path (e.g.: '<DATADIR>/Data/sourcedata_dropscans/').
Symlinking that folder from a shorter path (e.g. directly in a home directory), and pointing to that instead, fixes the issue.  Not sure where the root cause of this bug (char limit) is though??

**Comment by effigies** [comment]
The problem is that `sourcedata` is part of the dataset path. All files are being excluded because of this.

**Comment by effigies** [comment]
See:

https://github.com/poldracklab/fmriprep/blob/01a152d090fb7a43591f6ddd34e6101f4909b892/fmriprep/utils/bids.py#L155

**Comment by akhanf** [comment]
Ah ok I get it, I jumped to the wrong conclusion!  In my case I had 'derivatives' somewhere above the bids dataset in my path.

Is this behaviour likely to change in a future version? I.e. to only exclude those string matches in folders below the dataset, rather than above?

The particular example we have is data that has been pre-processed (gradient non-linearity correction), then fed into fmriprep, so input path is '.../dataset/derivatives/gradcorrected/"

**Comment by effigies** [comment]
It should be resolved correctly in the next release of pybids, at which point we can simply rely on that and stop passing additional arguments.
