### ISSUE TITLE
Broken process pool

### ISSUE THREAD

**Issue by danielkimmel** [poldracklab/fmriprep#1260]
Hello,

Since issue #1231, I've updated fmriprep-docker to 1.1.4 and am running on a single participant. However, the program crashed citing:
`exception calling callback for <Future at 0x7fefd5eecac8 state=finished raised BrokenProcessPool>`

Partial log is attached. (I couldn't find the saved logs in the output or work directories, so I just copied what was available in the terminal buffer)

Also note that at the very beginning of the terminal output (not shown in the attached file, but pasted below), there were some numpy exceptions I haven't seen before.

Finally, note that near the end of the attached terminal output, just before the crash, were some machine precision warnings I haven't seen before.

Thanks so much for your help!
Daniel

INITIAL TERMINAL OUTPUT:
```
bash-4.2$ ./mnt/staging/daniel/fmriprep/fmriprep_job1.sh
RUNNING: docker run --rm -it -v /home/dlk2148/mnt/staging/daniel/fmriprep/freesurfer_license.txt:/opt/freesurfer/license.txt:ro -v /home/dlk2148/mnt/labshare/daniel/BIDS:/data:ro -v /home/dlk2148/data/fmriprep/out:/out -v /home/dlk2148/data/fmriprep/work:/scratch poldracklab/fmriprep:1.1.4 /data /out participant --no-submm-recon --ignore slicetiming --participant_label 18070901 -w /scratch
/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
180823-15:23:27,212 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 1.1.4:
      * BIDS dataset path: /data.
      * Participant list: ['18070901'].
      * Run identifier: 20180823-152327_d381008d-3c3c-4d4e-8d69-f3ea13a360b9.


```
[terminal_output_2018_08_22.txt](https://github.com/poldracklab/fmriprep/files/2315463/terminal_output_2018_08_22.txt)

**Comment by effigies** [comment]
Hi @danielkimmel, sorry for the slow response.

Here's the error and a little context:

```
/usr/local/miniconda/lib/python3.6/site-packages/nipype/algorithms/confounds.py:1022: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.6/site-packages/nipype/algorithms/confounds.py:1022: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
/usr/local/miniconda/lib/python3.6/site-packages/nipype/algorithms/confounds.py:1022: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  betas = np.linalg.lstsq(X, data.T)[0]
exception calling callback for <Future at 0x7fefd5eecac8 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x7fefd5e91f28 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x7fefd5e7c1d0 state=finished raised BrokenProcessPool>

...
[Exception repeated 6 times]
...

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 342, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 184, in run
    self._send_procs_to_workers(updatehash=updatehash, graph=graph)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 336, in _send_procs_to_workers
    deepcopy(self.procs[jobid]), updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _submit_job
    result_future = self.pool.submit(run_node, node, updatehash, self._taskid)
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
```

A child process terminating abruptly generally means it was killed by the operating system, which probably indicates that fMRIPrep exceeded memory limits. It's unclear whether the killed process requested a large amount of memory, or if other processes were using a large amount and it was merely unlucky, but in any event, this is very likely to be a memory error.

Looking at the warning lines, it looks like several copies of (a|t)CompCor were being run simultaneously, which can use a reasonable amount of memory in high-pass filtering.

How much memory was available on your system? By default Nipype (and thus fMRIPrep) will assume that it can use up to about 90% of your system memory. You may want to consider restricting it using `--mem-mb` to more accurately reflect your available resources, or to artificially restrict it so that poor estimates of memory usage on our part don't cause crashes.

Please be aware that larger BOLD series can consume large amounts of memory, and there's not much we can do about it but try to improve our memory estimates to avoid conflicts. (See #857.)

**Comment by oliver-xie** [comment]
Hello, @effigies. We have been having similar issues with 1.1.4 using singularity on Sherlock. It just hangs there. 

For example,

> [Node] Running "validate" ("fmriprep.interfaces.images.ValidateImage")
exception calling callback for <Future at 0x7fb10eecbda0 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
...
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Another example,

> [Node] Running "bold_to_t1w_transform" ("fmriprep.interfaces.itk.MultiApplyTransforms")
exception calling callback for <Future at 0x7f3f43747d68 state=finished raised BrokenProcessPool>
...
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

The command I used is 

`module load system singularity
PYTHONPATH="" singularity run \
        -B $SPTH/data:/data \
        -B $SPTH/output:/output \
        -B $SPTH/work:/work \
        -B $HOME/license.txt:/license.txt \
        $HOME/singularity_images/fmriprep.img \
        /data /output participant --participant-label sub-01sess01pl01 sub-02sess01pl02 sub-03sess01pl03 sub-04sess02pl01 sub-05sess02pl02 sub-06sess02pl03\
        -w /work --fs-license-file /license.txt \
        --no-submm-recon --template-resampling-grid "2mm" \
        --use-aroma --aroma-melodic-dimensionality 50 --fs-no-reconall`

We requested 4 CPUs with 16G memory and our datasets are not very large (0.5G each session). Should I include --low-mem or specify --mem-mb to be 64G? Or is there anything wrong with our command?

Thanks a lot for your help!

Oliver

**Comment by oesteban** [comment]
Hi Oliver, if you are using sherlock, please double check that you are actually requesting enough memory. 

Please have a look into these submission scripts:

https://gist.github.com/oesteban/5947d28caf6c3750e0a2f2aa09102702

**Comment by oliver-xie** [comment]
Hi Oscar,
Thanks for the tip. 
I used the configuration in your script 
```
#!/bin/bash
#SBATCH --job-name=team1-6       
#SBATCH --time=5:00:00
#SBATCH -n 1                      # Each line of tasks_list.sh is an independent task
#SBATCH --cpus-per-task=16             
#SBATCH --mem-per-cpu=4G       # Take over all available RAM per node
# SBATCH --exclusive   
```      


 
This time fmriprep went further but still crashed before finishing with similar error. 

> [Node] Running "calc_median_val" ("nipype.interfaces.fsl.utils.ImageStats"), a CommandLine Interface with command:
fslstats /work/fmriprep_wf/single_subject_04sess02pl01_wf/func_preproc_ses_session_task_run_02_wf/ica_aroma_wf/bold_mni_trans_wf/merge/vol0000_xform-00000_merged.nii -k /work/fmriprep_wf/single_subject_04sess02pl01_wf/func_preproc_ses_session_task_run_02_wf/ica_aroma_wf/bold_mni_trans_wf/mask_mni_tfm/ref_image_corrected_brain_mask_maths_trans.nii.gz -p 50
exception calling callback for <Future at 0x7fed1dfbdf98 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
exception calling callback for <Future at 0x7fed1debd550 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)

I ran the same fmriprep workflow on my local machine and did not have a problem. Please let me know if the memory I requested is sufficient or not. I have been trying to play around with different configurations without much success.
  
Thank you in advance!

Oliver

**Comment by oesteban** [comment]
Hi @oliver-xie, sorry for the delay.

What is the output of slurm? With only 5h wallclock time I'd bet that it timed out before finishing.

Otherwise looks good, which means that it is taking a whole lot of memory. Strategies to minimize memory fingerprint are (in order):

1. Limit `--omp-nthreads` and `--nthreads` (right now you are using all 16 requested). I'd go first with something like `--omp-nthreads 8 --nthreads 12` and then reduce `--nthreads` to 10 or 8.
2. Limit `--mem-mb 30000` (a lot lower than the 64G you are requesting, this is correct)
3. `--low-mem`.

**Comment by oliver-xie** [comment]
Hi @oesteban. Thanks for the advice. For some reason, fmriprep usually runs for a couple of hours and just hangs there (instead of giving me an error message and stop) until it hits the walltime and gets killed. 
The slurm output before fmriprep hangs
> [Node] Setting-up "fmriprep_wf.single_subject_04sess02pl01_wf.func_preproc_ses_session_task_pictionary_run_02_wf.ica_aroma_wf.calc_median_val" in "/work/fmriprep_wf/single_subject_04sess02pl01_wf/func_preproc_ses_session_task_pictionary_run_02_wf/ica_aroma_wf/calc_median_val".
180918-11:06:00,206 nipype.workflow INFO:
[Node] Running "calc_median_val" ("nipype.interfaces.fsl.utils.ImageStats"), a CommandLine Interface with command:
fslstats /work/fmriprep_wf/single_subject_04sess02pl01_wf/func_preproc_ses_session_task_pictionary_run_02_wf/ica_aroma_wf/bold_mni_trans_wf/merge/vol0000_xform-00000_merged.nii -k /work/fmriprep_wf/single_subject_04sess02pl01_wf/func_preproc_ses_session_task_pictionary_run_02_wf/ica_aroma_wf/bold_mni_trans_wf/mask_mni_tfm/ref_image_corrected_brain_mask_maths_trans.nii.gz -p 50
exception calling callback for <Future at 0x7fed1dfbdf98 state=finished raised BrokenProcessPool>
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
 
After hanging for ~3h (estimated from the timestamp), the job hit the walltime and got killed.
I am currently running fmriprep using docker on my iMac, and it works most of the time, but we eventually want to move things to Sherlock.

**Comment by mnarayan** [comment]
I've run into similar issues as @oliver-xie on sherlock. It happens predictably during EPI registrations to T1w or MNI space. I automatically re-submit the participant level job for additional time (2 hours in my case) which seems to ensure the pipeline finishes to completion.

**Comment by oesteban** [comment]
@oliver-xie, @mnarayan did you finally find a solution to this issue?

**Comment by oliver-xie** [comment]
@oesteban I used the recommended configuration from https://gist.github.com/oesteban/5947d28caf6c3750e0a2f2aa09102702
and switched to a later fmriprep version 1.2.1, and the issue did not reoccur.

**Comment by oesteban** [comment]
Thanks very much. I'll close this for now. @mnarayan please check on @oliver-xie's solution and reopen if this is still happening to you.

**Comment by mnarayan** [comment]
I just ended up re-running and that worked. It doesn't seem to break as
often with recent release in any case.
