### ISSUE TITLE
output  in native/original space

### ISSUE THREAD

**Issue by a3sha2** [poldracklab/fmriprep#1376]
is there anyway to specify EPI output in native/orig space?

**Comment by effigies** [comment]
You mean corrected to each BOLD series' reference BOLD image, rather than aligned to the T1w image? Or would they be aligned to some subject-level mean BOLD?

**Comment by a3sha2** [comment]
yes, exactly

**Comment by effigies** [comment]
We don't currently support that, but it shouldn't be too hard to enable. Do you have any interest in submitting a pull request? We can orient you to the code and guide you through the process.

**Comment by chrisfilo** [comment]
I would love to learn more about the motivation for such a feature.

**Comment by jooh** [comment]
@chrisfilo the main motivation would be reuse of ROIs that are provided with BIDS-format datasets. It is fairly common to save ROI masks in native EPI space. That's what you see in e.g. [ds000232](https://openneuro.org/datasets/ds000232) and [ds001246](https://openneuro.org/datasets/ds001246).

This follows from the standard SPM pipeline, where coregistration is conventionally done by updating the affine in the header, and then only applied to the image data during normalisation to the MNI template. So if you use SPM-derived routines like [this one](https://github.com/jooh/roitools/blob/master/spm2roi.m) to construct ROIs you will end up with EPI-space ROI files.

Also, perhaps I'm a masochist but I actually like drawing my functional ROIs with native-EPI activations overlaid on the mean EPI so I can see what the image intensities look like... If you do this in fslview or mrTools you will end up with native EPI ROI masks.

It's not difficult to reslice the ROI mask, but you won't get the exact same voxels due to interpolation. And this seems an unnecessary imprecision.

Finally to clarify, @effigies, I don't know that you'd want these outputs aligned only to subject-mean BOLD. I think you would want to reproduce SPM behaviour, so the image data remains in EPI native space but have the updated header affine that brings them in registration with the native T1. This way you can still overlay anatomicals and functionals in sensible viewers (ie not fslview).
