### ISSUE TITLE
Question: workflow for releases?

### ISSUE THREAD

**Issue by jdkent** [poldracklab/fmriprep#1386]
I really like how fmriprep does releases: 
- linking the updated zenodo
- Giving a list of contributions (and who opened the pull request)
- Having a title for each release

I feel like there are a few manual steps that I don't know how to do. Maybe it would only benefit me, but I think it would be really awesome if one of the upcoming releases was screen recorded so it could be seen how it's done. (Or some other way of communicating the steps if that's easier)

Thanks!

**Comment by effigies** [comment]
Yeah, we don't have it written up, but it's pretty simple, and actually less effort than the following makes it sound:

1. We use [release-drafter](https://github.com/apps/release-drafter) to automatically generate the changelog.
2. When it's time to release, I copy that into [`CHANGES.rst`](https://github.com/poldracklab/fmriprep/blob/master/CHANGES.rst), cleaning up any entries for clarity, grammar, etc., and sorting types of change into `[FIX,ENH,DOC,RF,TEST,MAINT,CI]`, but otherwise maintaining order.
3. Commit `[skip ci] REL: <version>`
4. Signed and annotated tag (we don't always do this step, but it appears to help with between-release versioning)
5. Reformat the changelog entry into a release on GitHub
6. Once the Zenodo entry is created, I manually copy the DOI badge to the top of the GitHub release.

Docker and PyPI pushes are entirely done on CircleCI:

https://github.com/poldracklab/fmriprep/blob/f77f6171976ea28572604545ea0e845b8db83573/.circleci/config.yml#L676-L725

A lot of this could be scripted, using [`hub`](https://hub.github.com/) and the Zenodo REST API, but I think we're still in the phase where the total time to do it manually is less than the time needed to automate it.

**Comment by effigies** [comment]
@jdkent I think that's a great idea. Probably the best place for this is in the [Contributing to FMRIPREP](https://fmriprep.readthedocs.io/en/stable/contributors.html) section, or possibly adding a "maintainers" section.

**Comment by emdupre** [comment]
We made our RTD contributing section into a high level overview of our development philosophy, which I've found very helpful ! If there's interest in writing a similar section for FMRIPREP (maybe under the name "maintainers" !), I think it's quite nice to have there :+1:

**Comment by effigies** [comment]
@emdupre :+1: on that idea.

I've started a Google doc ([fMRIPrep development and maintenance guide](https://docs.google.com/document/d/1u8d1hi4bk09YsXmi0s8qYJEhxI9cQE7IMoso1M9swqU/edit)) where we can generate some content before we decide exactly how it will fit into the existing docs. Not sure how quickly we'll iterate, but if anybody feels inspired to take a stab, go for it.

cc @oesteban @chrisfilo

**Comment by chrisfilo** [comment]
Great initiative - I left some comments.
Best,
Chris
