### ISSUE TITLE
BIDS compliance Repetition Time Mismatch Bug

### ISSUE THREAD

**Issue by mnarayan** [poldracklab/fmriprep#1479]
My understanding is that if there is a mismatch in RepetitionTime between json sidecar and nifti header, then fmriprep should run without problems using the json sidecar information. However, this does not happen when I use version 1.2.5. 

I posted this question on Neurostars earlier but feel more certain now that this is a bug, so reposting here. For details please see
https://neurostars.org/t/bids-validation-error-repetition-time-mismatch-preventing-fmriprep-from-running/3343

This issue did not exist as of version 1.2.3 but does with 1.2.5, i suspect PR #1419 might have introduced the problem.

**Comment by effigies** [comment]
fMRIPrep has previously assumed that input datasets were BIDS compliant and more-or-less washed its hands of any failures resulting from non-compliance. However, these could be tough to identify at times, and we'd spend a while tracking down an issue that was eventually resolved with a fix that could be identified by the validator. So that's the motivation for adding it in.

You *may* skip validation with `--skip-bids-validation`, but I would recommend fixing your headers. We do take the `RepetitionTime` metadata field as authoritative, but I can't say the same will be true of all processing tools.

**Comment by effigies** [comment]
Almost, though it's probably best to say "Yes". I believe there are some issues that were deemed irrelevant to fMRIPrep that are ignored, though those may only have been warnings.

**Comment by oesteban** [comment]
I have opened #1484 to let fMRIPrep fail with a more clear error message. Sorry, I saw the neurostars question and this issue too late.
