### ISSUE TITLE
Output naming conventions 

### ISSUE THREAD

**Issue by KevinAquino** [poldracklab/fmriprep#1491]
Hi all,

We have been using fmriprep over two seperate versions and I have been noticing some names get changed e.g. the confounds file name gets changed to "confounds_regressors" or "probtissue" changing to "probseg". Does fmriprep spit out a mapping of names that can be called upon for different versions of fmriprep?

e.g. 
GM_PROBTISSUE_SUFFIX = ......
CSF_PROBTSSUE_SUFFIX = ......

We are a writing a little toolbox that uses fmriprep outputs and the naming conventions changing is hard to future proof the code. Its been by other people in my lab so I'm not sure if its because of different inputs (or incorrect spec. of input flags -- it doesn't look like it though). I could create one for our plug in, but it would be great if it already existed! :)

**Comment by effigies** [comment]
The changing conventions are because of the recent (August 2018) work on [BIDS derivatives](https://docs.google.com/document/d/17ebopupQxuRwp7U7TFvS6BH03ALJOgGHufxK8ToAvyI/edit#), which resulted in larger changes than any of us anticipated, going in.

That specification is in release-candidate mode, which means that only very minor changes will be accepted before being released as 1.0, mostly where it's found to be internally inconsistent. (After 1.0, no backwards-incompatible changes will be accepted until 2.0.)

The upshot is that our naming conventions should not be changing again. We don't have a name mapping like you describe, though that certainly would have been nice. If you need a fairly concise summary of the changes as the affect fMRIPrep, you can look through #1325 and #1333.

**Comment by KevinAquino** [comment]
Ok cool, thanks Chris thats very helpful!
