### ISSUE TITLE
phase encoding direction

### ISSUE THREAD

**Issue by yonestar** [poldracklab/fmriprep#1493]
Hello,

How is fmriprep determining phase encoding direction? On the html output reports, I am getting 
"Summary: Phase-encoding (PE) direction: Anterior-Posterior"

However, I believe my data is Posterior->Anterior. My scanning parameters as generated by the Siemens scanner say P -> A, and my json sidecars to the functionals have “PhaseEncodingDirection”:“j” and “InPlanePhaseEncodingDirectionDICOM”:“COL”, which I also believe mean P -> A.

I believe fMRIprep uses phase encoding direction for distortion correction, and if the phase encoding direction is read incorrectly, the SDC might warp might warp in an unexpected way

This is sort of a cross-post from https://neurostars.org/t/phaseencodingdirection-misreported-in-fmriprep-html-output/3403

Thank you!!
Yoni

**Comment by effigies** [comment]
Hi. So it looks like currently we just report the axis in our summaries, not the direction:

https://github.com/poldracklab/fmriprep/blob/dd4201caddaae6107f14553f84c5357757629c65/fmriprep/interfaces/reports.py#L180

I think I wrote this so that I knew which axis to expect correction along when inspecting a lot of reports, and the polarity was not very important to my purposes. But I agree that it would be less confusing to users if we did make the order indicate the direction of the encoding. Would you be interested in submitting a small patch?

**Comment by yonestar** [comment]
thanks @effigies !  So I think the patch might be as simple as:

```
pedir = {'i': 'Left-Right', 'i-': 'Right-Left', 'j-': 'Anterior-Posterior', 'j': Posterior-Anterior'}[self.inputs.pe_direction[0]] 
```

Yes? I am not 100% confident in my understanding of phase encoding, but that is what i understand

**Comment by effigies** [comment]
Yup. That looks right.

Looking at this, it does assume that the original image was in RAS orientation, which might be why I didn't do that, as many images come LPS, as well. So we would need to account for the image orientation before settling on this.

**Comment by oesteban** [comment]
Please reopen if the question is not fully answered and the new issue in SDCflows does not address the remaining issue of determining the actual PE direction when orientation is not RAS.

**Comment by xiaosonghe** [comment]
Hi! I have encountered the same issue. This time, regardless I set the PhaseEncodingDirection to j, or j- in my .json file (I had Philips data hence this information was not automatically generated by dcm2niix), when syn-sdc is turned on, I got the warning:"Incorrect phase-encoding direction, assuming PA (posterior-to-anterior)." 
Let's say it did not take the PE direction I fed in at all, then shouldn't it assume AP, as in the document, but not the PA? Thank you in advance for your help!

**Comment by unimusic** [comment]
Hi, I have a question that might be basic, but I can't find the answer anywhere. If I have an Axial scan, that goes from left to right, with RPI orientation, what would the corresponding phase encoding direction be? i, -i, j, -j, k, or -k?
How do these parameters map to the letters?

Thanks,

Angela

**Comment by effigies** [comment]
The three axes are indexed by `i, j, k`, and the axis codes indicate which direction you are moving by following an axis from its smallest index to its largest. RPI indicates that the `i` dimension increases from left to right, `j` from anterior to posterior, and `k` from superior to inferior. Therefore, if your phase-encoding direction is left-to-right, then the direction should be `i`. (`i-` would be from right to left in an RPI image.)

I would note that RPI is LAS reversed, so I would check to verify that you're describing it as I said above. It is not unheard of for people to use axis codes to refer to the side of the origin, rather than the direction of increase. In Python:

```Python
import nibabel as nb
img = nb.load(fname)
print(nb.affines.aff2axcodes(img.affine))
```
