### ISSUE TITLE
Check that files outside of derivatives are read only.

### ISSUE THREAD

**Issue by rwblair** [poldracklab/fmriprep#1505]
Might be nice to spit out a warning when running fmriprep on a dataset to see if any of the files are writable via permissions. Guarantee nothing is written to that shouldn't be written to.

**Comment by effigies** [comment]
That seems like a serious can of worms. Do we have instances of us writing over things we shouldn't? I set `fmriprep-docker` to mount everything but the output directory as `:ro` as both a safeguard and something that should hopefully produce a permissions error if we try to write to those directories. But if fmriprep starts performing these checks, we might start failing because we wrote the checks wrong, and they might only be wrong in certain environments...

**Comment by rwblair** [comment]
Good point.  Using the built in :ro seems like the easiest and most straight forward way to ensure this.
