### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by sandhitsu** [poldracklab/fmriprep#1533]
The Development Roadmap on the wiki simply says "WIP". Is there any more information someone can share at this point ? Are there plans to release periodic "stable" versions, or will it be simply ongoing incremental updates ?

**Comment by effigies** [comment]
So the problem here is that we have a very small team, with zero people on full-time fMRIPrep support, which makes a predictable roadmap difficult to generate. This is difficult in terms of not being able to predict our capacity to implement various features, but also in that working out the roadmap itself would be a significant time sink, while the actual features that get implemented are most often a function of bug reports and contributor interest.

So we're working toward a long-term stable strategy, and we're very happy to have contributor input in that direction. We consider this a community project, and interested members of the community are welcome to contribute as their interests, abilities and time permit.

As to stable releases, this implies a separate bug-fix process for each such release. For example, if we considered 1.2 and 1.3 stable releases, the "correct" way to handle that would be to fix bugs reported in 1.2.x and make a new release in the 1.2.x series in parallel with continued 1.3.x development. That's simply beyond our resources at present. So instead, we treat these 1.x.0 releases as indicating a fairly major update in functionality that users should be aware of, but there's no fundamental difference between the development process that goes into minor and micro version increments.

Our hope is that each release is usable, and our general recommendation is that users start with the most recent release. As they test it on their data, they can contribute bug reports and possibly fixes. Once their issues are fixed, we recommend that they stick with that version as they collect more data, only upgrading again when new bugs are found. And when users upgrade, we recommend that they re-run fMRIPrep on all of their data, not just the ones that produced the bugs.

Hopefully that makes the development process a little clearer.

**Comment by sandhitsu** [comment]
Chris: thanks for taking the time to write a detailed reply. That is very helpful, and I am sure the community appreciates your thoughts. I'll personally continue to use, test, report and help fix bugs as much as I can.

**Comment by emdupre** [comment]
.@effigies WDYT about adding that information to the wiki ? Would it make sense to put it under the "Roadmap" heading, or maybe "development philosophy" ?

**Comment by effigies** [comment]
@emdupre :+1:

**Comment by emdupre** [comment]
Done :heavy_check_mark: 

Thanks for bringing this point up, @sandhitsu, and for your help in making fMRIPrep !

**Comment by effigies** [comment]
Thanks, @emdupre! I fleshed it out a little, so hopefully it reads more clearly as a stand-alone document now.

I'll close this for now, but please reopen if further discussion is warranted.
