### ISSUE TITLE
Indicate that interpolation is NN above the EPI-to-T1w reportlet

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1538]
To avoid confusing the user (context: https://neurostars.org/t/fmriprep-weird-epi-t1-registration-artifact-problems/3811/2)

**Comment by sarenseeley** [comment]
Hi @oesteban, I added some explanation to the lines you indicated. Specifically, I added "_Note that Nearest Neighbor interpolation is used in the reportlets in order to highlight potential spin-history and other artifacts, whereas final images are resampled using Lanczos interpolation_." Let me know if this explanation is not accurate, or if you'd like me to change it in some other way.

Here's the edited file: https://www.dropbox.com/s/y6vz4aq4nzl9749/config.json?dl=0

**Comment by oesteban** [comment]
Hi @sarenseeley, would you mind creating a Pull Request for this?

Since you are modifying just one file, you should be able to add the explanation (which looks pretty good, IMHO) using this link https://github.com/poldracklab/fmriprep/edit/master/fmriprep/viz/config.json

The reason is that this way the changes will be assigned to your user and you'll become an fMRIPrep contributor.

**Comment by sarenseeley** [comment]
Done. Hopefully I did this correctly...

**Comment by oesteban** [comment]
You did! Thanks!
