### ISSUE TITLE
Fix circle caching of MNI templates

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#161]
Currently the MNI template cache is neither saved nor used, adding 15 minutes to the build time (maybe less?)

**Comment by oesteban** [comment]
?? -> https://github.com/poldracklab/fmriprep/pull/159

After that PR the cache folder is set in the circle cache and the mni template is downloaded and saved.

Is that PR not working? I've looked into the build and did not see any problem. Where did you see that it is adding 15min? I checked the build history, and we've around 45 min since we started to test both ds005 and ds054.

**Comment by shoshber** [comment]
Sorry for not closing the loop here. The command (https://github.com/poldracklab/fmriprep/blob/master/circle.yml#L23) doesn't check whether or not the cache exists, so for every build, `pip install` and `python -c '...'` run.

Looking at recent builds, both steps together have been taking < 1 minute so this is certainly low priority. When I first opened this issue, the `pip install` step was taking 15 minutes--no idea why that would be (https://circleci.com/gh/shoshber/fmriprep/139).
