### ISSUE TITLE
Ideas for mitigating high memory usage.

### ISSUE THREAD

**Issue by rwblair** [poldracklab/fmriprep#164]
Credit to @chrisfilo and @oesteban: We should look into transforming all operations done on 4d files done on a series of 3d files. This would allow for per process memory usage at any given time to be considerably lower.

@shoshber recommend looking at nilearn to handle file splitting as well since fslsplit seems to be slower than desired.

We also need to profile memory usage for the tools being used. This could be useful with the multiproc plugin to gauge if a given node will succeed with the current amount of memory available to it.

**Comment by shoshber** [comment]
Particularly need to profile interfaces that use all volumes at once, e.g. TCompCor & DVARS

Might be worth fixing https://github.com/nipy/nipype/issues/1663 and https://github.com/nipy/nipype/issues/1692 before using MultiProc

**Comment by oesteban** [comment]
I think @chrisfilo made a great stab at this problem with #223. Now it seems our bottleneck is more i/o derived. Closing.

We could open an issue in nipype though, in order to add some tools using nilearn for files splitting and merging, as @shoshber recommended. I think that this kind of interfaces will make it to nipype sooner or later. WDYT @satra?

**Comment by chrisfilo** [comment]
Things run without crashing now (which is great). We could achieve higher
parallelization factor (and potentially cut down runtime) if we
reimplemented motion correction on independent volume by volume
corregistration. This would only lead to improvement if I/O would keep up.

Alternatively we could try looking for a robust multithreaded motion
correction algorithm.
