### ISSUE TITLE
Module bold_std_trans_wf has no output called poutputnode.bold_aseg_std

### ISSUE THREAD

**Issue by shaohanyu2017** [poldracklab/fmriprep#1641]
Dear fmriprep experts,
When I am trying to run the latest version fmriprep (1.4.0) with the --output-space fsnative, I received the following error.  How I can solve the issue? With many thanks!

Exception: Some connections were not found
Module bold_std_trans_wf has no output called poutputnode.bold_aseg_std

Module bold_std_trans_wf has no output called poutputnode.bold_aparc_std

Module bold_std_trans_wf has no output called outputnode.bold_aseg_std

Module bold_std_trans_wf has no output called outputnode.bold_aparc_std

**Comment by lukassnoek** [comment]
I had the same error, which I think is caused by the `init_bold_std_trans_wf` function:

```python
freesurfer = [k for k in standard_spaces.keys()
                  if k.startswith('fs') and k != 'fsLR']
````

which later adds the `bold_aseg/aparc_std` nodes based on this `freesurfer` variable:
```python
if freesurfer:
        output_names += ['bold_aseg_std', 'bold_aparc_std']
```

It turns out that `standard_spaces` only includes spaces that are not part of the "non-standard references":

```python
NONSTANDARD_REFERENCES = ['anat', 'T1w', 'run', 'func', 'sbref', 'fsnative']
```

So, to circumvent this issue, I added `fsaverage` to my `--output-spaces`. Ideally, however, I'd like to get the aseg/aparc segmentations/parcellations also *without* specifying any freesurfer-based output space (e.g., only `T1w`). 

Would this be possible?

**Comment by oesteban** [comment]
> So, when you don't add some kind of "fsaverage*" output to your `--output-spaces` argument, fmriprep will crash. So, to circumvent this issue, I added `fsaverage` to my `--output-spaces`. Ideally, however, I'd like to get the aseg/aparc segmentations/parcellations also _without_ specifying any freesurfer-based output space (e.g., only `T1w`).
> 
> Would this be possible?

Sure, what you are describing is very related to #1631. Please feel free to reopen that issue and elaborate there on how you would like to see this implemented.

For now, I'll address this error independently of such conversation to avoid crashing for this reason.
