### ISSUE TITLE
Normalization 

### ISSUE THREAD

**Issue by Xin-cqu** [poldracklab/fmriprep#1664]
Hello, everyone. I have limited knowledge of fMRI andI want to use fMRIprep instead of spm12 to preprocess and analyze massive fMRI data. But I found that the final output of the two software are different, possibly for one reasons:

1. Normalization process

I also read the fMRIprep paper, which mentioned the difference between smoothing with other pipelines. The problem may arise in normalization . The final image of spm12 is 61-73-61, while that of fMRIprep is 75-77-45, which can not calculate and extract time series on ROI with AAL template. Please help me to see what caused it. Thank you.

**Comment by oesteban** [comment]
Hi @Xin-cqu,

I can't talk about SPM12, but I'm pretty sure that the output of fMRIPrep is:

  1. In MNI152NLin2009cAsym space (you'll find a reference and a full description of what fMRIPrep did in the "Methods" section of each participant's html report).
  2. It seems to me you used fMRIPrep defaults, so that grid will be fitting the MNI space but keeping the voxel size of the original image. [Since fMRIPrep 1.4.0 we've unified the way you can control the output resolution of images](https://fmriprep.readthedocs.io/en/latest/spaces.html).

If your goal is using the AAL atlas, I'd recommend you to run fMRIPrep making sure you include the following:

```
--output-spaces MNI152NLin6Asym:res-2
```
That will ensure you use FSL's MNI (identified with that ``MNI152NLin6Asym`` label) and resample in the original resolution number 2 of the template (which happens to be the 2mm isotropic, for which there are AAL regions). You can add other spaces to this ``--output-spaces`` flag. E.g., adding ``MNI152NLin2009cAsym`` or ``MNI152NLin2009cAsym:native`` (these two are equivalent) would generate your runs on MNI space with the grid of 75x77x45 you've seen this far.

If you can allow some time, I could give it a try and add AAL to TemplateFlow (the repository from which fMRIPrep pulls templates down). That would make it much easier for you to put all of this together.

**Comment by Xin-cqu** [comment]
Hello, @oesteban 
Thank you for your help. I'll try again as you told me. Wait until the results come out and then give another feedback. I will also read the documentation in detail to try to figure out how these custom processes should be set up. It would be better if the authorities could give a detailed tutorial including specific examples, just personal opinions.

**Comment by Xin-cqu** [comment]
Additionally, the dimension of the output image is related to the bounding box. So, is  there an option to specify bounding box provided by fMRIprep?

**Comment by oesteban** [comment]
> is there an option to specify bounding box provided by fMRIprep?

Not sure I understand the question, but outputs of fMRIPrep can be of two forms:

1) (default) The bounding vox is defined by the template image, and then a grid is fitted so that the final image resolution is the same as for the original BOLD image. Examples ``--output-spaces MNI152NLin6Asym`` or ``--output-spaces MNI152NLin6Asym:native``

2) The bounding-box and the gridding are defined by the template image. Example: ``--output-spaces MNI152NLin6Asym:res-2``, for the 2mm isotropic resolution.
