### ISSUE TITLE
DOC: Describe how to integrate custom templates

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#1693]
(related to #1640, in response to https://github.com/poldracklab/fmriprep/issues/1687#issuecomment-508995253)

**Comment by alexlicohen** [comment]
Sure, I can help with this; I need to learn more about this as well.

**Comment by oesteban** [comment]
@alexlicohen would you like to draft some text added to the end of https://github.com/poldracklab/fmriprep/blob/master/docs/spaces.rst ?

I could then review the draft and correct whatever you got wrong. That will highlight the friction points we want to get right at first.

**Comment by alexlicohen** [comment]
Sure, let me put something together. 

-Alex

**Comment by alexlicohen** [comment]
So, after reading through [https://github.com/poldracklab/fmriprep/blob/master/docs/spaces.rst#custom-standard-spaces](url), I feel that this is actually already very well explained and it is pretty clear how to add a custom standard space. The real issue is that I did not know that this page even existed until now!

The best fix would be to somehow add a link to that page of the documentation to the Usage section on output-spaces here: [https://fmriprep.readthedocs.io/en/stable/usage.html#Workflow%20configuration](url)

Thus making it obvious that there is a whole page describing how to use `--output-spaces`
