### ISSUE TITLE
Documentation Request: Provide suggested best practices for parallelization

### ISSUE THREAD

**Issue by gdevenyi** [poldracklab/fmriprep#1737]
It appears based on my initial reading thus-far, that while fMRIprep will run against a complete BIDS dataset, it does not parallelize across subjects. It does take advantage of multiple CPUs some semi-controllable, but undocumented ways (see #1736) based on which tool I'm sure.

I'd like to request some documentation be added regarding best practices for parallelization, useful information might include
- a tool to launch fmriprep against clusters https://github.com/pipitone/qbatch comes to mind here
- a way to run locally in parallel (qbatch supports this)
- some estimates on what tools inside fmriprep can take advantage of local parallelism for job packing purposes
- some estimates on what the memory requirements are for "common" datasets (1x1x1 iso T1W + bold) again to assist in job packing
- a warning be added if users run fMRIprep against a bids dataset with no subject selected, noting this probably isn't the best way to handle this

Some of this I can help with, but I'm not a fMRI guy, I'm supported a new deployment of fMRIprep and I want to make sure the users get the most out of the computing available to them

**Comment by AnonymousBoba** [comment]
There is a lot of great information and benchmarking here: https://neurostars.org/t/how-much-ram-cpus-is-reasonable-to-run-pipelines-like-fmriprep/1086/5

One subject per job is common but will randomly fail with multiple jobs for 1.4 <= version < 1.5.0 due to #1667.

**Comment by AnonymousBoba** [comment]
There was a suggestion in the aforementioned thread to add this to documentation, but I'm not sure if it was ultimately added. 

There is a caveat, of course, that some of this may not necessarily be applicable to current versions.

**Comment by oesteban** [comment]
Pinging @surchs here :) - Any chance you could contribute your benchmarks to the documentation?

**Comment by hao1ei** [comment]
Thanks for your invitation! @oesteban 
I also encountered the same problem, because of the huge amount of data, I have to transfer the data processing from the local to our cluster. Although our cluster has many nodes, due to the kernel version of the cluster is too low (centos 6) and administrator permissions, I can only install **singularity** (version=2.4.6, our administrator said that the use of docker requires administrator privileges) to use fmriprep. Since the node calls need to be queued, my solution is to separate the tasks into 30 shares, and then each task commits to reduce the thread's call (but not too little, which will slow down the processing, depending on each node's threads). The 1200+ subjects were processed in about 3 weeks (AROMA was used and fs-reconall was not used). I think my solution is not a clever way, and I hope that if fmriprep can add GPU-accelerated features later, it will be a big improvement.
