### ISSUE TITLE
PV of segmentation projected from T1 impedes aCompCor and CSF signal extraction

### ISSUE THREAD

**Issue by shoshber** [poldracklab/fmriprep#177]
Improve segmentation. See screenshot; voxels labeled "CSF" overlap the cortex
![screen shot 2016-11-08 at 4 41 05 pm](https://cloud.githubusercontent.com/assets/1402948/20123248/b281c8de-a5d2-11e6-8f7a-55cd7b8056e9.png)

@chrisfilo

**Comment by oesteban** [comment]
We'll need a little bit of context here. What is presented in the screenshot? Where the segmentation comes from? Was it running with the ```--debug``` flag?

**Comment by chrisfilo** [comment]
I think a few things might've been confused when creating this screenshot.
We should reeveluate the segmentation maps after transformation to EPI
space (for the purpose of signal extraction) when we run one of the beast
subjects.

**Comment by oesteban** [comment]
Ok, I guess we can close this one?

**Comment by chrisfilo** [comment]
Not until someone runs FMRIPREP on a full resolution subjects and checks if
the segmentation in the EPI space looks ok.

**Comment by chrisfilo** [comment]
This is still a problem:

![image](https://cloud.githubusercontent.com/assets/238759/20856332/36d84b3e-b8c1-11e6-9067-cfa674e4a32a.png)

It seems that when we convert the segmentation from T1 to EPI we get severe partial volume issues. The voxels corresponding to CSF around the brain overlap with grey matter to a great extent. I would not recommend using aCompCorr until we fix this.

One solution would be using better segmentation - switching to FreeSurfer will allow us to grab a mask for the ventricles alone - without the CSF around the brain.

**Comment by oesteban** [comment]
While FreeSurfer is not integrated, we could transform the posterior probability maps (or the PVEs, even better) and then apply a MAP criterium to obtain the segmentation. That will probably improve a lot the great amount of pixels classified as GM taking over the WM.

**Comment by chrisfilo** [comment]
We can just use tCompCorr for now.

**Comment by oesteban** [comment]
Ok, I'll update the title of the issue.

**Comment by chrisfilo** [comment]
This issue also impacts the CSF SignalExtration - I've updated the title accordingly.

**Comment by oesteban** [comment]
? - I don't see the new title :D

**Comment by chrisfilo** [comment]
There is a way to fix it without using FreeSurfer.

From the original paper http://www.sciencedirect.com/science/article/pii/S1053811907003837:
"Anatomical data were segmented into gray matter, white matter, and CSF partial volume maps using the FAST algorithm available in the FSL software package (Smith et al., 2004). Tissue partial volume maps were linearly interpolated to the resolution of the functional data series using AFNI (Cox, 1996). In order to form white matter ROIs, the white matter partial volume maps were thresholded at a partial volume fraction of 0.99 and then eroded by two voxels in each direction to further minimize partial voluming with gray matter. CSF voxels were determined by first thresholding the CSF partial volume maps at 0.99 and then applying a three-dimensional nearest neighbor criteria to minimize multiple tissue partial voluming. Since CSF regions are typically small compared to white matter regions mask, erosion was not applied.
