### ISSUE TITLE
fmriprep ignores --dummy-scans 0 when calculating aCompCor

### ISSUE THREAD

**Issue by psadil** [poldracklab/fmriprep#1904]
I think this is a bug, but if it's the desired behavior perhaps it's worth mentioning in the documentation. When `fmriprep` detects non-steady-state volumes, those volumes seem to be excluded from the aCompCor calculations, regardless of whether the `--dummy-scans` flag specifies that there are no non-steady-state volumes. For example, one component will be missing from a run in which the html report says "Non-steady-state volumes: 0 (Warning: 1 automatically detected)".

```
import pandas as pd
import numpy as np

json_file = 'run-with-non-stead-state-detected_desc-confounds_regressors.json'
regressjson = pd.read_json(json_file)
n_comps = regressjson.loc[:,np.asarray(regressjson.loc['Mask'] == 'combined')].columns.size
# in a run with 300 TRs, n_comps is less than 300 when non-steady-state 
# volumes were automatically detected
```

Ran with `fmriprep-docker`
fMRIPrep version: 1.4.0
fMRIPrep command: `/usr/local/miniconda/bin/fmriprep /data /out participant --output-space T1w fsaverage fsnative --ignore slicetiming --participant_label 05 06 --longitudinal --n_cpus 6 --dummy-scans 0 -w /scratch`

**Comment by jdkent** [comment]
Thanks for raising this issue, to provide reference for my thought process:
- [`skip_vols` is being passed to `bold_confounds_wf`](https://github.com/poldracklab/fmriprep/blob/1.4.0/fmriprep/workflows/bold/base.py#L647)
- [`skip_vols` is being passed to `ica_aroma_wf`](https://github.com/poldracklab/fmriprep/blob/1.4.0/fmriprep/workflows/bold/base.py#L856) (which was the primary reason the pull request was opened)
- the [test from the merged pull request does not test what happens when the number of dummy scans are in conflict](https://594-92465059-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html#datatype-func_desc-summary_suffix-bold_task-cuedSGT_run-1)

I'll replicate this condition from our tests and see if it occurs for the most recent version of `fmriprep`
