### ISSUE TITLE
help documentation in current unstable

### ISSUE THREAD

**Issue by satra** [poldracklab/fmriprep#1930]
i'm trying out the most recent unstable docker image for fsLR cifti output, and noticed a few things in the help output:

1.   freesurfer, fsLR and CIFTI
```
--output-spaces OUTPUT_SPACES [OUTPUT_SPACES ...]
                        "NKI", "OASIS30ANTs", "PNC", "fsLR", "fsaverage") or
```
just verifying that while this allows fsaverage, the cifti output is no longer in fsaverage space. do i need to explicitly specify fsLR when i also use `--cifti-output`?

2. two defaults:
```
   --fs-subjects-dir PATH
                        Path to existing FreeSurfer subjects directory to
                        reuse. (default: OUTPUT_DIR/freesurfer) (default:
                        None)
```
3. the wording confuses me
```
  --fs-no-reconall      disable FreeSurfer surface preprocessing. (default:
                        True)
```
i take this to mean that reconall is not run, not that all surface based processing is stopped. but each time, some part of my brain thinks the latter.

**Comment by effigies** [comment]
1) Output spaces are currently broken if you do try to use `fsaverage`. I am aiming to have this fixed by Monday.

2) Yeah, this is a problem with the argument parser. The first default basically says how "None" will be interpreted. The second is added by the parser.

3) No, it's the latter, unless something has changed recently. It used to be `--no-freesurfer`, but we now use other FreeSurfer tools, so the old name made people confused about providing a license file. But no recon-all means not trying to run recon-all, and not attempting to use the results of recon-all. Possibly with `--fs-subjects-dir`, we can change the logic, and replace `ReconAll` with `FreeSurferSource`.

**Comment by satra** [comment]
thanks @effigies - i'm running a single subject through - it's still running.
