### ISSUE TITLE
fieldmaps magnitude file does not exist

### ISSUE THREAD

**Issue by qasim85** [poldracklab/fmriprep#1943]
Hello
I am getting the following error
fMRIPrep failed: The trait 'in_files' of an IntraModalMergeInputSpec instance is an existing file name, but the path  '/mnt/sub-SAD024/ses-post/fmap/sub-SAD024_ses-post_acq-3_run-1_magnitude1.nii.gz' does not exist.

This problem was discussed in the past in https://neurostars.org/t/fmriprep-fieldmap-phasediff-error-file-magnitude2-not-found/712, but I think it was fixed and was also different than what I am having.
Here is my bids directory on fmap.

my_env[13:55][1.87][-87%]qbukhari@openmind7:sad$ ls  sub-SAD027/ses-post/fmap/
sub-SAD027_ses-post_acq-128_run-1_magnitude.json
sub-SAD027_ses-post_acq-128_run-1_magnitude.nii.gz
sub-SAD027_ses-post_acq-128_run-1_phasediff.json
sub-SAD027_ses-post_acq-128_run-1_phasediff.nii.gz
sub-SAD027_ses-post_acq-3_run-1_magnitude.json
sub-SAD027_ses-post_acq-3_run-1_magnitude.nii.gz
sub-SAD027_ses-post_acq-3_run-1_phasediff.json
sub-SAD027_ses-post_acq-3_run-1_phasediff.nii.gz
sub-SAD027_ses-post_acq-rest_run-1_magnitude.json
sub-SAD027_ses-post_acq-rest_run-1_magnitude.nii.gz
sub-SAD027_ses-post_acq-rest_run-1_phasediff.json
sub-SAD027_ses-post_acq-rest_run-1_phasediff.nii.gz

As we can see, the problem is, a missing '1' after the  file names magnitude  etc.   Any tips on solving this ?

Thanks a lot

best
Qasim

**Comment by effigies** [comment]
The [Fieldmap Data](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data) section of the BIDS standard enumerates ways of encoding fieldmaps. For [phase difference](Phase difference image and at least one magnitude image) fieldmaps, it specifies `_phasediff.nii.gz` along with `_magnitude1.nii.gz` and (optionally) `_magnitude2.nii.gz`.

The only suggestion I have for solving this is renaming your data to use `magnitude1` instead of `magnitude`.

**Comment by qasim85** [comment]
Sure, I can try this.. Thanks

**Comment by mgxd** [comment]
Hi @qasim85 - did this solve the issue?

**Comment by qasim85** [comment]
I hope it is solved. None of the subjects finished the analysis yet, so I cannot be sure. Running already for more than 20 hours. Satra suggested to move them to /nobackup/scratch  for faster  processing, but still taking a lot of time.

**Comment by oesteban** [comment]
Hi @qasim85 - did this solve the issue?

**Comment by qasim85** [comment]
This this solved the problem. Thank you
