### ISSUE TITLE
Mixing Version 151 and Version 159

### ISSUE THREAD

**Issue by dkp** [poldracklab/fmriprep#1987]
Dear Experts,

We struggled to get version 151r2 to behave consistently on the HPC in a Singularity container.  Nevertheless, we persisted and ended up doing a fair bit of processing with that Singularity container.  Recently, I have revisited the issue and pulled 159...at that point I saw there was a warning about 151r2 being unstable.  This was a relief (given our troubles with it). However, I am concerned.  Should we be thinking about rerunning all results we got with 151r2 or are the results similar enough (when it runs) that we can mix it with 159 results?

Thanks,

Dianne Patterson

**Comment by mgxd** [comment]
Hi @dkp - thus far, fmriprep has followed the [semantic versioning](https://semver.org/) scheme. In your case, the since the difference between versions is minimal (micro/patch version difference), I don't see the results differing much.

**Comment by dkp** [comment]
Thanks so much.

-Dianne
________________________________

**Comment by effigies** [comment]
1.5.x is one of the minor series where we respected that better, so that's your good luck. In the future we plan to be more consistent about separating improvements from bug fixes, so that you can be more sure that, if the first two numbers match, the results should be essentially interchangeable.

We'll also continue to note any significant changes in the [release notes](https://fmriprep.readthedocs.io/en/stable/changes.html).
