### ISSUE TITLE
Using "top-up" scans, to correct for spatial distortions

### ISSUE THREAD

**Issue by jawaltz** [poldracklab/fmriprep#2068]
Hi-

At the end of every run, we do a "top-up" scan in the opposite direction of acquisition (P-->A). This is done, in principle, to correct for the spatial distortions that might result from acquiring images in only one direction. We do the same with structural images. We only get ONE of these images, at the end of each run, so they are only 3-dimensional, but they also have accompanying sbref images.

What I'm wondering is if there is a way to feed these images into fmriprep, to be used for this purpose. Up to this point, I have only used functional images acquired in he A-->P direction, and just tossed the images acquired in the P-->A direction.

Has anyone else tried to solve this problem? If so, how?

Thanks,

Jim Waltz

**Comment by effigies** [comment]
If you have the data in BIDS format, we will find these automatically and apply them, unless you specify `--ignore fieldmaps`. See [Susceptibility distortion correction](https://fmriprep.readthedocs.io/en/stable/sdc.html).

**Comment by mgxd** [comment]
Closing this as it's gone stale, please reopen if you are still running into issues

**Comment by juliapottkaemper** [comment]
Hey, 

I was running into the same issue. I want to use top up scans for susceptibility distortion correction, but fmriprep does not recognize this scan. I put it in the same folder as the fmri 4D scan. However, if I run BIDS validator, it obviously tells us that the top up scan is no 4D value, therefore no valid BIDS format for an fmri scan. I am wondering where I should put the scan otherwise, or how to name it.. Could someone please help me? 

Cheers, Julia

**Comment by effigies** [comment]
It should go in fmap/ as an epi image. Please see the bids spec (MRI section).
