### ISSUE TITLE
--omp-nthreads no longer maxing out at 8

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2070]
Version: 20.1.0rc1

Without setting `--nthreads` or `--omp-nthreads`, I'm getting both set to nprocs.

The old formula for `--omp-nthreads` was `max(1, min(8, nthreads - 1))`.

This probably changed along with the massive configuration object.

**Comment by effigies** [comment]
Additionally, `--nthreads` is not being respected. I'm poking around a little...

**Comment by effigies** [comment]
> Additionally, `--nthreads` is not being respected. I'm poking around a little...

I can't reproduce this locally. No idea what's happening. Hoping that the average load on a 28-core run doesn't exceed 16 cores and get me punted from the node.

**Comment by soichih** [comment]
We are running fmriprep 20.2.1, and we started noticing cpu core spikes which leads to out-of-memory issue (probably too many processes running and using too much memory as aggregate)

![image](https://user-images.githubusercontent.com/923896/153948314-553b4271-9de8-4c2c-a1c8-c99a6c0f74bf.png)

We are trying to set the max core to 8, and for the most part, fmriprep seems to be honoring this number, except at the end as the graph shows. (red line is at 800%)

```
cat <<EOF > multi_proc.yml
plugin: LegacyMultiProc
plugin_args: {maxtasksperchild: 1, memory_gb: 14, n_procs: 8, raise_insufficient: false}
EOF
```

Should I not use multi_proc.yml anymore?

**Comment by soichih** [comment]
I will try setting --nthreads and --omp-nthreads and see if it limits the CPU cores.

**Comment by effigies** [comment]
Are you able to identify the processes that are filling up those high CPU spots?

And there should be a `.toml` file that's in your scratch directory (and it's also printed out almost first thing in the logs). Could you post that?

**Comment by soichih** [comment]
--nthreads and --omp-nthreads doesn't seem to cure it? I am still seeing some occasional bumps.. (could be just some artifact of how we are collecting information though..) 

![image](https://user-images.githubusercontent.com/923896/154754304-bb39ee3a-988d-4c54-961d-1b66ded854c8.png)

I've increased the thread counts to 16 with 30gb for vmem (it's 2022 after all!) so it doesn't get killed at the end when the memory usage spike happens.

![image](https://user-images.githubusercontent.com/923896/154754410-475196cb-3033-4182-be4f-fa7c60dde39c.png)

The process count spikes at the end seems to be caused by a large number of `antsApplyTransforms` processes.. I see 64 of them running near the end. We aggregate processes running within certain time window (it should be 30 seconds). So it's possible that, if tons of different processes gets run within 30 seconds windows, that might register as many concurrent processes when in face they are running separately in rapid succession. How long does each `antsApplyTransform` command run usually? 

Here is one of those 64 commands that it ran.

`
antsApplyTransforms --default-value 0 --float 1 --input /scratch/hayashis/job_9779068/work/fmriprep_wf/single_subject_9002_wf/func_preproc_ses_1_task_rest_wf/bold_split/vol0185.nii.gz --interpolation LanczosWindowedSinc --output /scratch/hayashis/job_9779068/work/fmriprep_wf/single_subject_9002_wf/func_preproc_ses_1_task_rest_wf/bold_t1_trans_wf/bold_to_t1w_transform/vol0185_xform-00185.nii.gz --reference-image /scratch/hayashis/job_9779068/work/fmriprep_wf/single_subject_9002_wf/func_preproc_ses_1_task_rest_wf/bold_t1_trans_wf/gen_ref/sub-9002_ses-1_T1w_ras_valid_corrected_xform_masked_reference.nii.gz --transform /scratch/hayashis/job_9779068/work/fmriprep_wf/single_subject_9002_wf/func_preproc_ses_1_task_rest_wf/bold_reg_wf/bbreg_wf/concat_xfm/out_fwd.tfm --transform /scratch/hayashis/job_9779068/work/fmriprep_wf/single_subject_9002_wf/func_preproc_ses_1_task_rest_wf/sdc_estimate_wf/fmap2field_wf/vsm2dfm/sub-9002_ses-1_phase1_rads_phdiff_unwrapped_recentered_filt_demean_maths_fmap_trans_rad_vsm_unmasked_desc-field_sdcwarp.nii.gz --transform /scratch/hayashis/job_9779068/work/fmriprep_wf/single_subject_9002_wf/func_preproc_ses_1_task_rest_wf/bold_t1_trans_wf/bold_to_t1w_transform/tmp-5zu0a5pc/mat2itk_pos-002_xfm-00185.txt
`

The *raw* data used to draw the graph is found here > https://dev1.soichi.us/tmp/_smon.out It's just a list of json object at various time

**Comment by effigies** [comment]
> How long does each `antsApplyTransform` command run usually?

It's resampling a single volume, so shouldn't take very long. I would expect <30 seconds. And these jobs are handled by an internal multiprocessing pool so will respawn as quickly as Python can manage.

**Comment by soichih** [comment]
The scratch directory gets wiped when the job finishes.. so I've updated the app to preserve it. I am rerunning the test job now. For me > https://brainlife.io/project/5d786647281b9525d8821011/process/6210043aff10f482da8ffaf0
