### ISSUE TITLE
Fieldmaps for multi echo data

### ISSUE THREAD

**Issue by njr175** [poldracklab/fmriprep#2230]
I brought this question / concern up at Neurohackacademy and @effigies suggested I open an issue here, and loop in @tsalo : 
We collected spin echo field maps (in 2 directions), and we have multi echo functional data. We weren't able to get the fieldmaps BIDS compliant until I added '_epi' (ex: sub-3040_ses-1_dir-ap_run-1_epi.nii.gz). However, fMRIPrep ignored the fieldmaps. I then edited the .json files to include the 'IntendedFor' statement. fMRIPrep then acknowledged the fieldmaps, but used them incorrectly as they are not EPIs. The ‘after’ images for the ‘Susceptibiltiy distortion correction’ looked like they were overcorrected. We’re wondering if having the spin echos labeled as _EPI files causes fMRIPrep to make assumptions about the files? Our spin echos are not EPIs. Could this be causing a problem? (The fMRIPrep boiler plate is also incorrect for our preprocessing stream as it refers to our spin echos as “two echo-planar imaging (EPI) references with opposing phase-encoding directions”.)
This also has been discussed on Neurostars, but with no conclusion: https://neurostars.org/t/getting-fieldmaps-or-other-multi-echo-data-into-bids-format/1854/6 
We're wondering if there is/should be a way to get our fieldmaps BIDS compliant without having to include the _EPI (which we *think* is the problem). Thank you!

**Comment by tsalo** [comment]
To clarify, your field maps fall under [Case 4: Multiple phase encoded directions ("pepolar")](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar) of the BIDS specification, correct?

If so, then it is appropriate to label them as `_epi`, even though they're spin echo. That's actually the way they're described in the specification:

> The phase-encoding polarity (PEpolar) technique combines two or more **Spin Echo EPI** scans with different phase encoding directions to estimate the underlying inhomogeneity/deformation map.

An example dataset that should have equivalent field maps and multi-echo fMRI data is [OpenNeuro/ds002156](https://openneuro.org/datasets/ds002156/versions/1.0.0). Would you mind taking a look at the metadata for those field maps to see if they're similar, or to at least clarify the differences between your data and his?

Would you also be willing to share images before and after distortion correction, so we can see what the overcorrection looks like?

@Shotgunosine noted issues with PEPOLAR field maps and multi-echo fMRI data in #2150, although the issue was with report generation, rather than the distortion correction itself. Based on the issue, I assume that the distortion correction worked well. Is that correct, @Shotgunosine?

**Comment by Shotgunosine** [comment]
As far as I could tell the distortion correction was working appropriately. @njr175, if you're seeing overcorrection is it possible that the phase encode direction is not labeled correctly?

**Comment by JulioAPeraza** [comment]
Thanks @tsalo . I have explored that in my data, and the images seem overcorrected.
The re-application of the fieldwarp to the image (#2236 ) may be producing this overcorrection because the fieldwarp is a non-idempotent operation.  
Thanks!

**Comment by njr175** [comment]
So sorry for my delay in responding to all of this. 
Thank you, @tsalo  for the explanation RE labeling with _EPI. The clarification is helpful. I did check @Shotgunosine point about making sure the files were named in the right direction, and they are. I've attached before and after pictures showing what I was referring to as overcorrection. As you can see, there's some posterior areas that look very strange in the corrected images - some spots that look like they're being 'pulled'?  (specifically, x=20, z=29)

Yes, I can try rerunning with poldracklab/fmriprep:unstable

![Sus Distortion_Before](https://user-images.githubusercontent.com/13022158/91863490-2c61f980-ec3d-11ea-9629-3ed85e0e4e9f.PNG)
![Sus Distortion_After](https://user-images.githubusercontent.com/13022158/91863506-308e1700-ec3d-11ea-9ac0-e4aee0155331.PNG)

**Comment by njr175** [comment]
@tsalo Our issue must have been with #2236 because re-running with poldracklab/fmriprep:unstable fixed our overcorrection that was happening! Thank you!
Quick follow-up question: Is this unstable version going to be incorporated into the next fMRIPrep version release, or should I go ahead and preprocess my data with fmriprep:unstable version? 
Thanks so much for all of your help!

**Comment by effigies** [comment]
This will be in the next release, 20.2.0. There is currently a release candidate 20.2.0rc0 while we do some final testing. Anticipated full release is September 28. If you want to verify that 20.2.0rc0 works for you or report any bugs that come up before then, that would be a great help.

Closing this as it seems resolved.

**Comment by njr175** [comment]
Thanks for this information! Yes - resolved on our end!

Sure thing - I will re-run on vs. 20.2.0rc0 to check if it still works for us and/or report back any bugs found.
