### ISSUE TITLE
Poor INU correction

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#2279]
Tracking some subjects that appear to have poor INU correction in 20.2.0rc0. Should rerun with 20.2.0rc2 to see if the latest changes make any improvements. I would not consider this blocking, however.

The following list will be updated as cases are encountered.

* [x] ds001 / sub-13
* [x] ds001 / sub-16
* [x] ds231 / sub-04
* [x] ds1021 / sub-A00008326

@jbwexler could you rerun these?

### What version of fMRIPrep are you using?

20.2.0rc0

### What is the exact command-line you used?
```
<place your command line here>
```

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
<please copy&paste all the information you can gather about errors>
```

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by jbwexler** [comment]
No problem, they're running now.

**Comment by oesteban** [comment]
DS001 is already on sherlock after 20.2.0rc2 - `/oak/stanford/groups/russpold/data/openneuro.org/derivatives/ds000001/fmriprep-20.2.0rc2/fmriprep/`

Both look acceptable to me:

sub-13:
<img width="1280" alt="Screen Shot 2020-09-25 at 2 50 00 PM" src="https://user-images.githubusercontent.com/598470/94269087-78ebdc80-ff3e-11ea-9ef3-0382b4169391.png">

sub-16:
<img width="1280" alt="Screen Shot 2020-09-25 at 2 50 08 PM" src="https://user-images.githubusercontent.com/598470/94269126-843f0800-ff3e-11ea-9193-eb1ae2eb8233.png">


The first one (sub-13) is pretty interesting from a QC perspective because of the several artifacts that seem to be happening at the same time. Surprising that its surface reconstruction is usable.

**Comment by effigies** [comment]
Agreed. Those look better.

**Comment by effigies** [comment]
ds231 much improved.

**Comment by effigies** [comment]
All noted subjects improved by 20.2.0rc2.
