### ISSUE TITLE
Proposal: run workflows from installed path inside Docker

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#301]
To avoid that installation errors like #300 pass unnoticed, we could/should run the smoke tests from the general installation path inside docker.

That would require a regular installation (using ```python setup.py install```) instead of a development installation, and implicitly help test that the package installation works well.

WDYT?

**Comment by shoshber** [comment]
It's a good idea.

Would using `python setup.py install` instead of `pip install -e .` make it more difficult to iterate quickly when using singularity images on TACC? That would be my only concern.

**Comment by chrisfilo** [comment]
One advantage of `pip install -e .` over `python setup.py install` is that the former resolves dependencies and in this way is similar to installation from pypi. Maybe the solution would be to do both.

In general - because we don't provide easy way to install non-python dependencies (ants, fsl, c3d, freesurfer) I would not stress out about issues with pip installation and recommend users to use containers (BTW stampede KNL now supports Singularity - with whooping 272 hyper-cores per node!).

**Comment by oesteban** [comment]
What is the standpoint on this?

Am I I right if say that now we consider `python setup.py install` better for singularity, since you can supersede the installed package by setting the new path with sources in the `PYTHONPATH` with higher priority?

**Comment by chrisfilo** [comment]
I was able to use PYTHONPATH with the current Docker setup to take
precedence over internal libraries without having to regenerate the
container. It was the -e flag that made the difference.

**Comment by effigies** [comment]
I believe this was resolved in #381.
