### ISSUE TITLE
Skip fieldmap unwarping if it does not improve coregistration

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/fmriprep#438]
Run EPI-T1w twice - with and without fieldmaps and check which one works better (final similarity score). Make it clear on the report if fieldmaps were skipped.

**Comment by oesteban** [comment]
This could work, but checking the final similarity score is a bad idea since they are not absolute values. A good registration with fieldmap applied may have a lower similarity score easily.

If we find another way to check this, then it might optimize the results.

**Comment by oesteban** [comment]
After a lot of thinking through this idea, I've reached the conclusion that it would be pretty dangerous:
- What if one subject out of 50 goes without susceptibility distortion because of this?
- How many times this feature will hide away that there are problems with the fieldmap option (e.g. wrong parameters, noisy fieldmap) that should be addressed and prefer going on with the result that "looks better".
- I'm becoming more and more convinced that _susceptibility distortion correction should be always done; if it screws up your data then worry about your original data and look at them closer_.

**Comment by oesteban** [comment]
(feel free to disagree and please reopen in that case)
