### ISSUE TITLE
DOC: Some graphs are failing to build in RTD

### ISSUE THREAD

**Issue by effigies** [poldracklab/fmriprep#441]
https://fmriprep.readthedocs.io/en/latest/workflows.html#bold-preprocessing

**Comment by effigies** [comment]
Missing from latest:

* [`basic_wf`](https://fmriprep.readthedocs.io/en/latest/workflows.html)
* [`fmriprep.workflows.epi.bold_preprocessing`](https://fmriprep.readthedocs.io/en/latest/workflows.html#bold-preprocessing)
* [`fmriprep.workflows.epi.ref_epi_t1_registration`](https://fmriprep.readthedocs.io/en/latest/workflows.html#epi-to-t1w-registration)

Not clear what these have in common.

**Comment by effigies** [comment]
I think the issue here is that these three pipelines all include `BBRegisterRPT`, which is [having problems](https://readthedocs.org/projects/fmriprep/builds/5306365/) with the `init='coreg'` option. I'll look into this.

**Comment by chrisfilo** [comment]
Seems like a python 2 vs 3 problem.

On Tue, Apr 18, 2017 at 12:59 PM, Chris Markiewicz <notifications@github.com

**Comment by chrisfilo** [comment]
I managed to switch RTD to python 3.5, but the error is still there.

**Comment by chrisfilo** [comment]
Ok so the problem is that nipype cannot figure out the version of FREESURFER, so it defaults to 5.3 and sets the input spec that does not allow 'coreg'. I tried [fooling RTD environ into thinking FreeSurfer is installed](https://github.com/poldracklab/fmriprep/commit/734889d632b1f4a734b6ea0f3fb6a428c7902df9), but the environment variable does not seem to propagate to the build step.

Ideas?

**Comment by effigies** [comment]
Probably can update niworkflows to bias towards the v6 input spec better. I'll check it out first thing in the morning.


-------- Original message --------
