### ISSUE TITLE
Reports are getting big again

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#478]
A single report for Beast (with 5 runs and fieldmaps) can be 40Mb. Situation will get even worse in UH2 where there are 12 tasks across two sessions. Things to consider:

- Drop some visualisations (maybe we can make aCompCor and its visualisation optional?)
- Crop some plots (for example FAST)
- Split the report into multiple files (one per run + one for anat and fieldmaps)
- Try to improve compression (try [Guetzli](https://research.googleblog.com/2017/03/announcing-guetzli-new-open-source-jpeg.html) for example)
- Reduce number of tiles for some plots

**Comment by oesteban** [comment]
From those 5 I would go for this (in this priority):
1. split reports in multiple files
2. remove aCompCor
3. reduce number of tiles for some plots (for example FAST, instead of cropping)

**Comment by IanEisenberg** [comment]
I don't think we need one report per run, but maybe some would prefer that. Perhaps a flag indicating how you want the reports to be split? Per-run, per-session or just one report?

**Comment by oesteban** [comment]
After considering this issue, I'm reaching to the following conclusions:

1. The size of the html is not a big deal per se. I find the most annoying that large html reports just crash the browser. So, maybe the right fight here is making the reports digestible by browsers, more than reducing the size. One idea would be this: https://github.com/jonathantneal/svg4everybody . We would have then the main html + one single, big svg, and this library loads the appropriate panel from the big file when you need to render it in the browser (meaning, only one svg loaded at a time).
2. That said, I think we can do some things without giving up on some of the reportlets:
  * Plot together: BOLD brainmask, aCompCor and tCompCor masks. Each contour with a different color. Having only one bitmap instead of 3 will definitely reduce sice.
  * Plot together: FSL FAST and T1w brain mask. Or better: FAST contours but rendered on the whole image (so we can see the skull).

WDYT?

**Comment by chrisfilo** [comment]
The low hanging fruit of dealing with browser crashes is checking if disabling embedding of all the png and svg files (replacing it with relative links - in other words many files per report) solves the issue. My hunch is that it might help a lot.

**Comment by oesteban** [comment]
A short investigation of this led me to think like that. Apparently, the browser does not render anything until it is shown in the viewport. The problem we might be hitting is the excessive number of elements hanging in the DOM. Any strategy to reduce them (e.g. writing isolated files) in theory will help.

Let's test that first - stripping the embedded svg from the html and save them standalone. If we feel like having only one file then we can check https://github.com/jonathantneal/svg4everybody.

**Comment by oesteban** [comment]
I'll close this for now and refer the discussion/ideas recollection to a wiki I've just created https://github.com/poldracklab/fmriprep/wiki/Notes-on-the-organization-and-size-of-reports
