### ISSUE TITLE
Rename '--ants-nthreads` to `--omp-nthreads`

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#499]

**Comment by effigies** [comment]
Does it make sense to rename `--nthreads` while we're at it? I'm not sure the difference between that and `--omp-nthreads` will be as obvious when it's no longer apparently ANTs specific.

We need to indicate a difference between within-process and across-process thread maxima.

We should probably also assert that `nthreads >= omp_nthreads`, otherwise nipype will just hang at the first OpenMP-enabled process.

**Comment by chrisfilo** [comment]
What would you rename `--nthreads` to?

BTW we also need to support `--n_cpus` alias to `--nthreads` since this is in BIDS Apps spec.

+1 for the assert

**Comment by effigies** [comment]
Yeah, I'm not sure of what a better option is. Though we could also *just* use `--n_cpus`.

Pushing a change where I just update the docstring on `--nthreads` to be a little clearer.
