### ISSUE TITLE
BOLD skullstripping failure

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#573]
https://openneuro.org/datasets/202020206473303030303137/versions/3030303031372d3030303031?app=FMRIPREP&version=5

**Comment by effigies** [comment]
I can't see any error information. Is the "Download" link when looking at logs supposed to result in this (or similar) file?

```HTML
<!DOCTYPE html>
<html>
    <head>
        <base href="/"></base>
        <meta charset="utf-8">
        <!-- SITE IS NOT RESPONSIVE // Works better on mobile devices without this
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
        -->
        <title>Stanford Center for Reproducible Neuroscience</title>
        <link id="favicon" rel="icon" type="image/png" href="/assets/favicon.ico" />
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,300italic,400italic,700italic|Cabin:400,400italic' rel='stylesheet' type='text/css' />
        <link rel="stylesheet" href="main.573c1447.css" />
        <script type="text/javascript" src="/assets/papaya.js"></script>
        <!-- Google OAuth -->
        <script src="https://apis.google.com/js/client:platform.js"></script>
    </head>
    <body>
        <div id="main"></div>
        <script src="https://d3tvtfb6518e3e.cloudfront.net/3/opbeat.min.js"
        data-org-id="6f7a08376feb4427bc9a9310960358ae"
        data-app-id="3b8e3e7b79">
        </script>
        <script type="text/javascript" src="app.min.706a3dfd.js"></script>
        <script type='text/javascript'>
            (function (d, t) {
                var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
                bh.type = 'text/javascript';
                bh.src = '//www.bugherd.com/sidebarv2.js?apikey=1vbvmixxz2qvrucshcwueg';
                s.parentNode.insertBefore(bh, s);
            })(document, 'script');
        </script>
    </body>
</html>
```

This could just be chromium being buggy, too...

**Comment by chrisfilo** [comment]
I manged replicate the openneuro bug. Will report to squishy.

Check out the HTML reports to see the error and problem with skullstripping.

**Comment by chrisfilo** [comment]
Here's a direct link to the report: https://s3.amazonaws.com/openneuro.outputs/b2b76d1b40fe1196eb7db904aaf4bdf1/dbe4fea4-386f-4877-a87c-936e828d479b/fmriprep/sub-3.html

It's ds000017.

**Comment by effigies** [comment]
Oh right. Sorry, I did see that, and even wrote a response. Forgot to press the "Comment" button, though.

**Comment by chrisfilo** [comment]
Same thing with the latest release: https://s3.amazonaws.com/openneuro.outputs/b2b76d1b40fe1196eb7db904aaf4bdf1/898585de-8029-4350-9796-4d5c83902f97/fmriprep/sub-6.html

**Comment by effigies** [comment]
Yeah, I'll start a run replicating this and should be able to track down the issue on Wednesday.

**Comment by effigies** [comment]
This dataset has been throwing up a number of bugs, and I think it's down to bad headers:

```Shell
$> fslhd /data/bids/ds000017_R2.0.0/sub-3/ses-timepoint2/func/sub-3_ses-timepoint2_task-probabilisticclassification_run-02_bold.nii.gz               
filename       /data/bids/ds000017_R2.0.0/sub-3/ses-timepoint2/func/sub-3_ses-timepoint2_task-probabilisticclassification_run-02_bold.nii.gz

sizeof_hdr     348
data_type      INT16
dim0           4
dim1           64
dim2           64
dim3           33
dim4           182
dim5           1
dim6           1
dim7           1
vox_units      mm
time_units     s
datatype       4
nbyper         2
bitpix         16
pixdim0        0.000000
pixdim1        3.125000
pixdim2        3.125000
pixdim3        4.000000
pixdim4        2.000000
pixdim5        0.000000
pixdim6        0.000000
pixdim7        0.000000
vox_offset     352
cal_max        0.0000
cal_min        0.0000
scl_slope      1.000000
scl_inter      0.000000
phase_dim      0
freq_dim       0
slice_dim      0
slice_name     Unknown
slice_code     0
slice_start    0
slice_end      0
slice_duration 0.000000
time_offset    0.000000
intent         Unknown
intent_code    0
intent_name    
intent_p1      0.000000
intent_p2      0.000000
intent_p3      0.000000
qform_name     Unknown
qform_code     0
qto_xyz:1      3.125000  0.000000  0.000000  0.000000
qto_xyz:2      0.000000  3.125000  0.000000  0.000000
qto_xyz:3      0.000000  0.000000  4.000000  0.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Left-to-Right
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Unknown
sform_code     0
sto_xyz:1      0.000000  0.000000  0.000000  0.000000
sto_xyz:2      0.000000  0.000000  0.000000  0.000000
sto_xyz:3      0.000000  0.000000  0.000000  0.000000
sto_xyz:4      0.000000  0.000000  0.000000  0.000000
sform_xorient  Unknown
sform_yorient  Unknown
sform_zorient  Unknown
file_type      NIFTI-1+
file_code      1
descrip        FSL4.0
aux_file
```

Both the qform and sform are marked "Unknown". mricron complains about a bad affine (and shows as `np.diag([0, 0, 0, 1])`). FreeSurfer''s `mri_info` describes the orientation as `???`. nibabel reads it as `LAS`, for reasons that aren't clear to me.

While we could make an attempt to canonicalize the incoming BOLD files, in a case like this, where orientation information has to be guessed, I'm not sure it's a good idea to set headers and proceed as though valid data were presented.

**Comment by chrisfilo** [comment]
The headers for this dataset were supposed to be corrected https://openfmri.org/dataset-orientation-issues/

The best course of action in FMRIPREP would be to catch such problems, correct them, but also provide a big fat warning in the report.

**Comment by effigies** [comment]
Just FYI, this is R2.0.0, that I downloaded from openfmri.org to reproduce the issue.

So what do we want to do when we conform BOLD series? Use nibabel's ["best-guess" approach](https://github.com/nipy/nibabel/blob/c6e06d91c30e1d9e9b43cc8cd03c94afe5a07e74/nibabel/nifti1.py#L726-L733) to establishing the affine, and then setting the `sform`? Or if there's a valid qform (despite a 0 code), to set the qform code to `SCANNER`?

**Comment by chrisfilo** [comment]
@suyashdb could you look into the issue with this dataset? The headers were suppose to be fixed, but they do not seem to be. Maybe wrong files were included in the 2.0.0 release?

@effigies I don't have deep knowledge on how to best handle this. Going with nibabel seems a good choice.

**Comment by oesteban** [comment]
@effigies "best-guess" approach from nibabel + setting the `sform` seems to me the best option. Of course with the big-fat warning.

**Comment by effigies** [comment]
Linking to #260, since this is relevant to the issues raised there.

I've been digging into nibabel a little bit more to get a grip on the situation. To summarize (and invite critique) prior to diving into a PR:

I'm defining an invalid header as one with `qform_code == 0` and `sform_code == 0`. In [this case](https://github.com/nipy/nibabel/blob/c6e06d91c30e1d9e9b43cc8cd03c94afe5a07e74/nibabel/nifti1.py#L726-L733), nibabel will simply take the pixdims and create an [appropriate affine](https://github.com/nipy/nibabel/blob/c6e06d91c30e1d9e9b43cc8cd03c94afe5a07e74/nibabel/analyze.py#L640-L664), with the intercepts at the midpoint of the middle voxel.

This will produce an `LAS` afffine, defined so based on the [Analyze-era presumption](https://github.com/nipy/nibabel/blob/c6e06d91c30e1d9e9b43cc8cd03c94afe5a07e74/nibabel/analyze.py#L67-L76) that images are saved in "radiological" orientation.

So, **the plan**: In the absence of a valid header (`(qform_code, sform_code) == (0, 0)`), we will set the `sform` to the derived LAS-oriented affine, and set the `sform_code` to 1 (`NIFTI_XFORM_SCANNER_ANAT`) to indicate that we haven't performed any alignment to an anatomical.

Worth noting: [How does ANTs handle qform and sform in NIFTI 1 images?](https://github.com/stnava/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F). I think we should be okay with setting just the `sform`, given that we (by assumption) have an invalid `qform`.

To address further issues raised in #260:

* If we change the orientation of input files we need to adjust the phase encoding direction as well.

NIfTI does have a `phase_dim` header entry. We could update the header, and use that later.

* Applying those fixes to big 4D _bold files will create an (almost) identical copy and waste a lot of disk space

True, and adding the PE direction header entry will cause the same issue, if we don't already need to create a new file.

I haven't tried this out yet, but we could consider creating a `filename.hdr.gz` with a data offset matching the original header, and symlink to the original file with `filename.img.gz`. Assuming this works, we couldn't reorient, but we could update the headers without copying the data.

----

Okay. Now I'll start work on a PR implementing **the plan**, but let me know if anything seems amiss, or worth further discussion.

**Comment by chrisfilo** [comment]
Seems sound to me.
