### ISSUE TITLE
Proposal to speed up builds

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#589]
General case: the latest image is pulled down, and the software is patched in the image (mounting).

If it is a tag push or there is certain value (like `force_build`) in the commit message, the image is built and the source is not patched in.

WDYT?

**Comment by effigies** [comment]
The problem there is that every commit in a branch that needs rebuilds is going to have to have `force_build` in its commit message, otherwise it will just patch.

I think the idea is fine in general, but I'm not sure the logic can be nicely achieved with no state apart from `:latest` + commit message.
