### ISSUE TITLE
Interface TCompCorRPT failed to run

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#652]
As reported here https://neurostars.org/t/fmriprep-tcompcorr-crashes-on-empty-array/668, tCompCor gets an `IndexError: cannot do a non-empty take from an empty axes.`

**Comment by effigies** [comment]
Was able to reproduce locally.

**Comment by effigies** [comment]
The problem here is with the [erosion step](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/interfaces/utils.py#L150-L153). `iterations` ends up being 10, while anything greater than 5 produces all zeroes.

This is going to be a consequence of the partial FOV.

What about resampling the anatomical brain mask into BOLD space, and eroding that, instead of assuming the BOLD brain mask will be brain-shaped?

**Comment by oesteban** [comment]
+1 to your idea of resampling the anatomical brain mask and eroding that one. Actually, it'd be even better to erode in anatomical space where we have good resolution and then map into BOLD once eroded.

A second thing we could use is generating a [ball](http://scikit-image.org/docs/dev/api/skimage.morphology.html#skimage.morphology.ball) of a certain radius predefined *in mm* and only one iteration of erosion rather than 5 or 10.

**Comment by chrisfilo** [comment]
I see the problem now. Weird that it affects t and a compcor so differently.

The reason why I used the BOLD mask was that I wanted to capture
distortions and signal dropouts which will not be present in the anatomical
mask.

**Comment by effigies** [comment]
The problem with the ball, as far as I can see, is that we're not guaranteed that the origin of any given space is in any particular center. If we normalize to MNI, then we can create a ball there, and transform it back...

Or we could go full FreeSurfer (#433) and map T1w to MNI, map the MNI origin back into T1w, and recenter the image.

@chrisfilo I suspect that if we're eroding 30mm, the effect of drop-out is going to be miniscule.

**Comment by oesteban** [comment]
I don't understand this:

> The problem with the ball, as far as I can see, is that we're not guaranteed that the origin of any given space is in any particular center.

**Comment by effigies** [comment]
And I think eroding in T1 space, rather than BOLD is a good idea for both aCompCor and tCompCor. It seems like our over-erosion of WM in aCompCor might be an product of resampling before thresholding/eroding. (At the very least it shouldn't introduce distortion to switch.)

@oesteban It's possible I didn't understand what you were suggesting with the ball. I thought you were saying that, instead of starting with a mask of the brain, create a ball in the center of the brain.

**Comment by oesteban** [comment]
Ball - sorry, yes, I propose to use a ball with an specific radius as structuring element for the erosion, rather than iterating on the erosion. My suspicion here is that the structuring element is not very regular (probably a square), and that plus the big voxels of the BOLD space, plus the several iterations of erosion completely remove the mask.

I think eroding in the subject's T1 space should suffice here.

The ball will have a radius in voxels dependent on the voxel size. This also points to eroding in T1 space.
