### ISSUE TITLE
nan for medial wall

### ISSUE THREAD

**Issue by satra** [poldracklab/fmriprep#679]
for the gifti files mapped to fsaverage5, would it be possible to make the values on the medial wall nan ?

**Comment by chrisfilo** [comment]
Theoretically it should be as straighforward as adding a function node
after gifti conversion that would use nibabel to replace zeros with NaNs.
There might be a more reliable way to detect what is the medial wall though.

**Comment by effigies** [comment]
This shouldn't be hard. I'll re-check the FSFAST code to see how they do masking.

**Comment by effigies** [comment]
We're already using the cortical mask so the medial wall is 0. So it would need to be an additional step, equivalent to the following:

```Python
import os.path as op
import numpy as np
import nibabel as nb

cortex = nb.freesurfer.read_label('derivatives/freesurfer/fsaverage5/label/lh.cortex.label')
func = nb.load('derivatives/fmriprep/func/sub-01_task-rest_bold_space-fsaverage5.L.func.gii')

medial = np.delete(np.arange(len(func.darrays[0].data)), cortex)

for darray in func.darrays:
    darray.data[medial] = np.nan

func.to_filename(...)
```

So for us to go ahead and do this, we'd want to be sure that making it `NaN` would play well with FSFAST, FSL and SPM. Do you know how that would go, @satra?

We could also make this an optional preprocessing step, e.g. with a `--medial-surface-nan` (or similar) flag.

**Comment by satra** [comment]
@effigies - i'm happy with the optional flag. FSL definitely wouldn't like it, SPM wouldn't care, and FSFAST, i don't know. also, i would be fine with using lh.cortex as well. so whether you make this an explicit change is totally up to you guys.

**Comment by effigies** [comment]
Okay. If you're fine using your own filter for now, we're trying to focus on bugs rather than adding new features and flags in the run-up to the 1.0 release, so I'm going to mark this as low-priority for now. (@chrisfilo if you think this should be prioritized, let me know.)

That said, outputting masks that make working with our outputs meaningfully easier would be worth the effort of squeezing in before 1.0, IMO. So if, e.g., it would be a useful input to your toolchain to have the cortex labels as GIFTI label files instead of FS label files, we could do something like that.
