### ISSUE TITLE
Zenodo: change title of the record

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#804]
Replace the current "poldracklab/fmriprep" by "FMRIprep: a robust preprocessing pipeline for task-based and resting-state fMRI data" to make it match the title of the OHBM poster.

**Comment by chrisfilo** [comment]
I don't think this can be done easily with current setup. The issue is that the title should include both the name of the poster and the current version. This can be edited after the release (without changing the DOI). We would have to do this for each release.

Alternatively we can switch to pushing releases to zenodo via API, but that would require a lot of tooling.

**Comment by oesteban** [comment]
Oh I see. It seemed easy at first. Can you make me admin of the repo at zenodo? Just in case we really get into this.

**Comment by chrisfilo** [comment]
I could not find this feature https://github.com/zenodo/zenodo/issues/1325
