### ISSUE TITLE
Merging T1ws failed

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#841]
![image](https://user-images.githubusercontent.com/238759/33030300-d44515ae-cdcf-11e7-96e2-82842a10256c.png)

https://s3.amazonaws.com/openneuro.outputs/f85e0d83b3a5b45e3efd90854d6130a5/67629e33-bb62-41ff-8fbb-2068df24a514/fmriprep/sub-20.html

https://openneuro.org/datasets/ds000148/versions/00001?app=FMRIPREP&version=32&job=67629e33-bb62-41ff-8fbb-2068df24a514

**Comment by effigies** [comment]
Yeah, I've seen `mri_robust_template` fail if the images start out so extremely misaligned. I've been a bit hesitant to automatically adjust the affines so that the RAS center is near the center of mass, since that would add an additional transform that needs accounting for, and would be unexpected in the case of a single image (and perhaps unwelcome, if the user has manually set the center of the image).

We could add something like `--autocenter-t1w` that would add a step that would set the RAS center to the center of mass before attempting a merge. That keeps the default behavior unchanged, and requires the user to indicate that they're okay with modifying the T1w space in this way.

**Comment by chrisfilo** [comment]
I would switch it around - enabled by default, disabled by a command line option.

**Comment by effigies** [comment]
This would be backwards incompatible with all previous runs, unless an input image affine was coincidentally centered at the center-of-mass.

What about this:

1) Calculate center-of-mass for each image, yielding transform `aff_com_i` for *i*-th image
2) Apply difference to all but first image: `inv(aff_com_0) * aff_com_i`

This would keep the first image space as the output space, but should give enough of a hint to `mri_robust_template` to fix this issue.

**Comment by chrisfilo** [comment]
Sounds good!

Best,
Chris

**Comment by oesteban** [comment]
After looking at the T1w images in this dataset, I'm under the impression that one of them is actually a T2-FLAIR image. I've reported this to openfmri to confirm the lead.

That would explain the very poor performance of the template on all subjects in this dataset.

For now, I'd suggest just removing the `acq-sagittal` image from the BIDS tree and rerun.

**Comment by oesteban** [comment]
Removing the `acq-sagittal` fixed this issue.
