### ISSUE TITLE
Use MultiProc even when --n_cpus=1

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#855]
Remove Linear at all would fix memory issues in single-threaded execution.

**Comment by effigies** [comment]
Just a quick reminder that the reason we stuck with linear for `--nthreads 1` was so that we could have linear node processing with multi-threading in individual nodes. Resource management will need to be updated with an option to permit nodes that require more cores than the "maximum cores" to be run. (At least if we want to port the current behavior to MultiProc.)

Sorry if this is unclear. I can define terms more precisely and restate if whoever is looking into this issue needs.

**Comment by chrisfilo** [comment]
This is a good point, but why didn't this show up in @oesteban tests already? Were none of them with a single MultiProc worker?

**Comment by effigies** [comment]
We enforce `omp_nthreads < n_procs` if `n_procs > 1`. If `n_procs == 1`, we use linear. So single MultiProc worker is not easily done through the command line. I think we'd have to use a `--use-plugin` flag to make it happen in the current architecture.

**Comment by oesteban** [comment]
It should be fairly easy after this change: 

https://github.com/poldracklab/fmriprep/pull/854/files#diff-b93ab0122f4b2ac6738b896651cac6ccR335

and after the PR to nipype where we enabled this:

https://github.com/poldracklab/fmriprep/blob/992a61fc91f59ae6d88ef0ba48ab446df63892ae/fmriprep/cli/run.py#L281

**Comment by effigies** [comment]
You're right. I'd forgotten that we'd already handled the other side of this (allowing too-large jobs if nothing else is running) in nipype.

https://github.com/nipy/nipype/blob/6a57e3efdd67b8522890c6b38c0573f90dfc660e/nipype/pipeline/plugins/multiproc.py#L253-L254
