### ISSUE TITLE
Workflow for multiecho data

### ISSUE THREAD

**Issue by emdupre** [poldracklab/fmriprep#884]
I see in #808 that you're encouraging the creation of a unique workflow instead of modifying the `init_func_preproc_wf` as I've been doing in #875. Do you have a preference for either creating unique workflows for specific cases (like functional-only or multi-echo scans) or modifying existing workflows in place?

**Comment by oesteban** [comment]
Well, I think your route is better. In #808 we took that path because it seemed easier for new contributors to start that way. 

In sum, I think you have plenty of experience with nipype that allows you to advance quickly even implementing things the hard way. The way you were driving this PR is preferable (IMHO).
