### ISSUE TITLE
Bad BOLD skullstripping in ds000157

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/fmriprep#902]
![image](https://user-images.githubusercontent.com/238759/34182731-55c11958-e4cc-11e7-851b-97db0850be10.png)

ds000157 sub-23_task-passiveimageviewing

**Comment by oesteban** [comment]
Weird:
<img width="905" alt="bold_mask" src="https://user-images.githubusercontent.com/598470/34264899-3094c48c-e629-11e7-86a6-a03f0505b72c.png">
Just got this running this subject. I've tried with and without `--fs-no-reconall`. It remained consistent. Docker image :1.0.0 official.

**Comment by effigies** [comment]
What about with and without `--force-syn`? Because we re-compute BOLD masks after applying fieldmap correction, if I remember correctly.

**Comment by oesteban** [comment]
That's a reasonable explanation

On Dec 21, 2017 08:34, "Chris Markiewicz" <notifications@github.com> wrote:

What about with and without --force-syn? Because we re-compute BOLD masks
after applying fieldmap correction, if I remember correctly.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/fmriprep/issues/902#issuecomment-353396298>,
or mute the thread

**Comment by oesteban** [comment]
With `--force-syn`:

![bold_mask_ds157](https://user-images.githubusercontent.com/598470/34268279-f6ae0d44-e634-11e7-9c06-127dce783ceb.png)

**Comment by oesteban** [comment]
Apparently, the `N4BiasFieldCorrection` in the reference generation workflow didn't make any correction to the intensity. However, using my local version gave me the same result I have with the docker image. Running it multiple times with multithreading didn't change anything (actually, it seems like `N4BiasFieldCorrection` does not spawn multiple threads, or it does not have time to spawn with these little EPI images).

**Comment by oesteban** [comment]
https://sourceforge.net/p/advants/discussion/840261/thread/354df4c0/#116c
