### ISSUE TITLE
Fix random seed for ANTs brain extraction?

### ISSUE THREAD

**Issue by feilong** [poldracklab/fmriprep#917]
I ran fmriprep on the same dataset twice and got slightly different results. It seems to be caused by `init_skullstrip_ants_wf` and `antsBrainExtraction.sh`, which use random seeds from the internal random number generator by default. Does it make sense to add an extra parameter to fix the seed and make the pipeline deterministic?

**Comment by oesteban** [comment]
I don't think that will solve the problem. While it is possible that the run-to-run irreproducibility is caused by the random seed, our experience says that the real cause is multithreading.

Compile-time optimizations of the internal `ANTS` for registration to the template in `antsBrainExtraction` break run-to-run reproducibility, and some minimal differences in the masks can be seen.

When running without `--no-fs-reconall` (i.e. running with surface reconstruction) a new mask refinement step has been included that should help getting always the same mask.

Alternatively, we could add a flag to make ANTS work in single-threaded mode to ensure the reproducibility.

Finally, right now you can test with `--omp-nthreads 1` that `antsBrainExtraction.sh` produces always the same exact mask. But the cost is that all multithread-capable processes will be slowed down.

**Comment by feilong** [comment]
I think both random seeding and multithreading matter here.  In my case, the brain masks were exactly the same with fixed seed and single thread, but different when random seed was used.  By default `init_skullstrip_ants_wf` doesn't specify `t1_skull_strip.use_random_seeding`, which makes `antsBrainExtraction.sh` use random seeding and caused my problem.

**Comment by oesteban** [comment]
Got it. Sounds very reasonable.

However, if you need this anytime soon we are pretty swamped ATM. I would invite you to contribute with the patch. I can give you the support along the process.

**Comment by feilong** [comment]
Does it make sense to simply change those lines (https://github.com/poldracklab/fmriprep/blob/master/fmriprep/workflows/anatomical.py#L546-L549) to the following code? It just changes the default value because I don't see any reason to keep the option to use random seeding.
```
    t1_skull_strip = pe.Node(
        BrainExtraction(dimension=3, use_floatingpoint_precision=1, debug=debug,
                        keep_temporary_files=1, use_random_seeding=False),
        name='t1_skull_strip', n_procs=omp_nthreads)
```
