### ISSUE TITLE
HTML files are not displayed properly

### ISSUE THREAD

**Issue by bkraft4257** [poldracklab/fmriprep#945]
The HTML files are not displayed properly in FireFox and Safari. I have verified this on multiple machines with different versions of both.  The HTML files display properly in Chrome.  I have attached a zip file fo the HTML file in question. 
[sub-04.html.zip](https://github.com/poldracklab/fmriprep/files/1674549/sub-04.html.zip)

The screen shot below shows Chrome on the left, Firefox upper right corner, and Safari lower right corner.  

![image](https://user-images.githubusercontent.com/10143816/35524041-478f3b34-04ee-11e8-949b-46d30e485685.png)

**Comment by effigies** [comment]
This is the result of a decision to use webp for superior image compression to PNG. It seems Chrome is the only browser that correctly renders webp. As a back-burner issue, we've discussed moving to a fast JPEG variant (#142).

However, now that we are no longer directly encoding the images into the HTML, perhaps it's best to revert to PNG in the short term.

**Comment by TomEmotion** [comment]
This issue is quite a problem for those of us with sysadmins who do not wish to install Chrome for whatever reason. Also worth pointing out that the [example fmriprep output](http://fmriprep.readthedocs.io/en/latest/_static/sample_report.html) in the documentation does not render in other browsers either, which will stump many current and potential users:
